DefiLlama/defillama-server

src/getChart.ts, src/protocols/data.ts
This is an attempt to fix https://defillama.com/chain/Optimism (see image below for current state)
Didn't have env vars so was not able to validate locally. While it might also be a good idea to handle the case where no data is returned on the frontend, this would presumably fix the root cause.
=> fix /chain/Optimism

defi/src/protocols/data.ts
https://007vasy.github.io/
because of the different name, the Pyth oracle integration count is lower than in the defillama data
@Nemusonaneko 
the 3 should will 4 with this correction
=> renaming all Pyth, Pyth Network oracles to Pyth

defi/src/protocols/data.ts, defi/src/protocols/data2.ts
This PR adds the `openSource: false` field for projects where `chain: "Solana"` in files `defi/src/protocols/data.ts` and `defi/src/protocols/data2.ts`
The criteria by which a project is marked as not open source is simply whether or not their smart contract is publicly viewable on the project's associated git host.
=> Add `openSource: false` where applicable

defi/src/protocols/data.ts
Old link returns 404, new address is obtained from their twitter: https://twitter.com/thalesmarket.
=> Update Thales website

defi/src/protocols/data2.ts
Hey!
Someone has changed Uplift DAO's website link. This has been reported by one of our community members.
Is there a way to make sure that these changes are made only by the people who are part of the Uplift GitHub organization (https://github.com/UpliftDAO)?
=> Changed Uplift website link

defi/src/protocols/data2.ts
BCT is just one of the pool tokens that
we have enabled to be pooled but should
not be associated as our main protocol
token.
=> Remove pool token from description

defi/src/storeLiquidations.ts
Instead of binning the data, we serve data of all parsed liquidable positions. Also make the shape more portable for aka multichain support in the future. 
Reasoning for not binning here is that this is gonna be a lower level api cuz on the frontend users will be able to filter out chains. Will have another api (api route or inside getStaticProps while ISRing) to allow users stack chains or protocols and so on
=> Rewrite /liquidations endpoint's response format

defi/src/protocols/data2.ts
Just an update to include Cega into the Pyth TVS, kindly check
https://twitter.com/cega_fi/status/1533819362376916994?s=20&t=U9w1HZ9erWv8jSpLAgev_w
=> Cega Oracle Update to Pyth

coins/src/adapters/index.ts, coins/src/adapters/utils/erc4626.ts, coins/src/adapters/yield/mean-finance/index.ts, coins/src/adapters/yield/mean-finance/mean-finance.ts
At [Mean Finance](https://twitter.com/mean_fi), we are about to launch our new Yield-While-DCA product. This product uses ERC-4626 for yield-bearing tokens, so we deployed [Yield Daddy's](https://github.com/timeless-fi/yield-daddy/) Aave v3 adapters in both Optimism and Polygon
The thing is that we are currently using your price APIs in different parts of Mean, and these new tokens were not supported. So we are now adding support so that anyone can price them
We created a ERC4626 adapter so that in the future, it is easier to add new ERC4626 tokens
=> feat: add mean finance tokens

coins/src/adapters/yield/yearn/yearnV2.ts
The decimal resolver for PPS does not return correct decimals when the Vault is new and the PPS is 1e<decimals>
This is demonstrated in Yearn vault `0xF6B9DFE6bc42ed2eaB44D6B829017f7B78B29f88`.
Before the fix:
Expected: 18
Actual: 17
After the fix:
Expected: 18
Actual: 18
=> Fix Yearn PPS decimals resolver

defi/src/utils/normalizeChain.ts
Add L1 type for the Milkomeda A1 chain.
This PR continues the thread (https://github.com/DefiLlama/defillama-server/pull/1236)
=> Update Milkomeda A1 type

defi/src/protocols/data2.ts
Dear llama sers, kindly check these two protocols to add under the Pyth oracle
Aurigami
Beluga Protocol
Links below:
https://twitter.com/aurigami_PLY/status/1595059540055449601?s=20&t=M7_WZl7GuUWCam5qY50JZA
https://docs.beluga.so/dex/oracle
=> Add Pyth to protocols integrated

coins/src/adapters/index.ts, coins/src/adapters/markets/jarvis/index.ts, coins/src/adapters/markets/jarvis/jarvis.ts
We want to add support for jFIAT tokens on Mean Finance, but we realized that almost all of them were not available on Coingecko. So the idea would be to price them directly on the coins API, so that we can add them to our ecosystem
The idea will be to price the tokens based on the Chainlink feeds they use to maintain the peg
=> feat: add jarvis network tokens

defi/src/protocols/data2.ts
We've updated Metavault.Trade protocol info. Metavault.Trade made update on short and long leverage from 30x to 50x now.
=> fix: Metavault.Trade Protocol Info

defi/src/protocols/data2.ts
This change re-adds the USK collateral to the TVL for Kujira using kujira/index.js.
=> Re-add kujira/index.js to cover USK

coins/src/adapters/markets/jarvis/jarvis.ts
This commit adds the jBRL token and PriceFeed Aggregator address to the config of Jarvis in `coins/src/adapters/markets/jarvis/jarvis.ts`.
=> Add jBRL to getPrices config

coins/src/adapters/nft/chainlink/priceFeeds.ts
ArtBlocks aggregates a couple of different collections under a single contract (Fidenza, Ringers) so it's not straightforward to provide a price feed for these collections as the list stands.
=> Remove Art Blocks price feed

defi/src/protocols/data2.ts
Update data to reflect gmx deployment as well as convex, also the protocol does not have a token
=> Update Pirex data

defi/src/protocols/data2.ts
Think it's more accurate to categorize Sudoswap alongside Caviar, Blur, and other NFT marketplaces vs Uniswap, Sushiswap and other dexes.
=> Change Sudoswap category to NFT Marketplace

coins/src/adapters/yield/mean-finance/mean-finance.ts
We are now disabling Euler's 4626, since their contracts were frozen and we can't calculate how to convert from the 4626 to their underlying. Therefore, we can't calculate the price
=> fix: disable euler

coins/src/adapters/utils/erc4626.ts, coins/src/adapters/yield/mean-finance/mean-finance.ts
We realized that blacklisting tokens was not the best approach, specially because:
1. In the case of Euler, if they un-freeze their smart contracts, it would be nice to be able to calculate the correct price without having to remove the tokens from the blacklist
2. We should prevent this from happening again
So the idea is simple: if the 4626 fails for some reason, simply ignore it and don't calculate a price for it
=> fix: dont fail if wrong 4626

defi/src/protocols/data.ts, defi/src/protocols/data2.ts, defi/src/protocols/parentProtocols.ts
Ondo v1 and Ondo Finance are completely separate endeavors from different organizations. Ondo v1 was a DeFi-native protocol supported by an offshore (Cayman) foundation. Ondo Finance, a US-based entity, has separately launched centralized regulated security tokens like OUSG. We are supportive of preserving the historical record related to Ondo v1 through its own page in defillama but need to avoid confusion with the regulated products issued out of Ondo Finance today.
=> Fix issue associating Ondo Finance v1 and Ondo Finance

coins/src/adapters/yield/mean-finance/mean-finance.ts
Hey llamas!
This is a very small change from us. We currently support several ERC4626 adapters, but we realized that we wanted to be able to price other ERC4626 that were not being used directly within our DCA product. So we basically built a new endpoint that exposes all known ERC4626
=> [Mean Finance] refactor: use transforms api for 4626

coins/src/adapters/index.ts, coins/src/adapters/markets/aktionariat/aktionariat.ts, coins/src/adapters/markets/aktionariat/index.ts
Add price adapter for security tokens traded over the Aktionariat platform. 
Confidence hard coded to 1 as this is the only official price source for these security tokens.
=> Add Aktionariat 

defi/src/protocols/data2.ts
Link contains audits for Maker and Aave. Plus audits on new Spark code & deployment.
=> added audits to Spark

coins/src/adapters/yield/mean-finance/index.ts
We are simply adding support for a new chain on our coin adapters
=> feat: add support for bnb for mean finance adapters

defi/src/protocols/data.ts, defi/src/protocols/data2.ts
gm
submitting this for your review:
https://twitter.com/redstone_defi/status/1657037951614832642
and requesting to add RedStone as an oracle for Yield Yak.
Rationale: A potential misprice would mean a cascade of liquidations and automatic withdrawal of Yield Yak’s TVL 
Additional materials:
- RedStone <> YY codebase: https://github.com/redstone-finance/redstone-oracles-monorepo/tree/main/packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/yield-yak
- Utilisation of the feeds: https://dune.com/hatskier/redstone
(So far there've been 35k+ transactions including YY token prices processed on Avalanche C-chain)
thanks
=> add RedStone as an oracle to Yield Yak 

defi/src/protocols/data.ts
gm,
submitting for your review:
https://twitter.com/redstone_defi/status/1659260446011179010
Source code: https://github.com/redstone-finance/redstone-oracles-monorepo/tree/main/packages/on-chain-relayer/contracts/custom-integrations/mento
and requesting to add RedStone as an oracle for Mento & Moola-market (Moola uses same oracle flow as Mento).
https://twitter.com/redstone_defi/status/1659544475696521216
and requesting to add RedStone as an oracle for Pangolin.
Rationale: A potential misprice would mean a cascade of liquidations and automatic withdrawal of Pangolin's TVL.
RedStone <> Pangolin codebase: https://github.com/redstone-finance/redstone-oracles-monorepo/blob/main/packages/oracle-node/src/fetchers/evm-chain/avalanche/evm-fetcher/sources/dex-lp-tokens/PangolinLP.abi.json …
=> added redstone oracles to mento, moola, and pangolin

coins/src/adapters/tokenMapping_added.json, coins/src/adapters/yield/beefy/beefy.ts, coins/src/adapters/yield/misc4626/tokens.json
plvGLP was incorrectly set up to track the price of GLP 1:1. It's an ERC4626 token, so I added it as one. The Yama plvGLP vault has been added as well.
=> Fix plvGLP and add Yama plvGLP

defi/src/protocols/data.ts, defi/src/protocols/data2.ts
gm,
we would like to request adding RedStone as an Oracle for:
1. Voltz
https://twitter.com/redstone_defi/status/1666853320575836161
2. Float Capital
https://twitter.com/gelatonetwork/status/1640800952901828608
3. Y2K
Passed proposal with implementation:
https://commonwealth.im/y2k-dao/discussion/11435-rff-onboarding-redstone-as-an-oracle-service-provider-for-future-y2k-vaults
4. Vesta Finance
https://twitter.com/redstone_defi/status/1667185359757737988
Thanks,
Matt
=> Add RedStone Oracles to Voltz, Y2K, Vesta, and Float

coins/src/adapters/tokenMapping.json
This PR requests that the MNTA token be added to Kujira. 
MNTA is a native token on Kujira created through the token-factory module.
=> Add MNTA to Kujira

defi/src/protocols/data.ts
TVS methodology by @0xngmi here: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/6254
According to the Venus Protocol Docs, they imply a "Resiliant Oracle" approach. 
They have a Main Oracle, a Pivot Oracle and a Fallback oracle. 
The main oracle is being used when it falls within reasonable range of the pivot oracle. 
If this isn't the case, the Fallback oracle is used, but also checked if it falls within reasonable range of the Pivot Oracle. 
As such, the main oracle can be attributed TVS to, as it is used primarily.
The Pivot Oracle can also be attributed TVS to, because the primary oracle is *only* used when it falls within a reasonable range of the Pivot. 
The fallback oracle ***cannot*** be attributed TVS to as it is merely used when the pivot oracle determines that the …
=> Remove Binance Oracle from Venus TVS

defi/src/protocols/data.ts
TVS methodology by @0xngmi here: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/6254
dForce initially used BAND Oracles. 
According to their documentation they rely only on Chainlink Oracles now.
Announcement of Chainlink: https://twitter.com/chainlink/status/1372158309994790913?s=20
Documentation of dForce: https://docs.dforce.network/faq-and-guides/faq#how-do-you-source-price-feeds
=> Update Oracle specs on dForce

defi/src/protocols/data.ts
TVS methodology by @0xngmi here: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/6254
Loopring utilizies Chainlink oracles. 
They've introduced Band as a price source to display prices on their **frontend only**. 
This was heavily critizised by the industry to claim to be securing Looping. 
To note Band secures **nothing** on-chain in regards to Loopring. 
Here an article for further clarification: https://cryptoslate.com/only-chainlink-loopring-clears-recent-band-protocol-integration-rumors/
[Here ](https://twitter.com/ChainLinkGod/status/1301284583908864000?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1301284583908864000%7Ctwgr%5Ef3ec2aa76864d4bf1e267270859932503560b96b%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fcryptoslate.com%2Fonly-chainlink-loopring-clears-recent-band-pr …
=> Remove Band Oracles from Loopring

defi/src/protocols/data.ts
TVS methodology by @0xngmi here: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/6254
Pangolin is a DEX that issues LP tokens. Redstone prices these LP tokens to be used by other protocols to utilize in e.g. lending platforms. You can read about that [here](https://blog.redstone.finance/2023/05/19/redstone-x-pangolin-unleashing-defi-potential/).
It is important to note that Pangolin's TVL is in no way secured by Redstone. They merely price their LP tokens to be used by other protocols. One such integration is [DeltaPrime](https://defillama.com/protocol/deltaprime), that allows Pangolin LP tokens to be used on Avax. The TVL of DeltaPrime is hence correctly attributed to Redstone's TVS. The Pangolin TVL is wrongly attributed to Redstone's TVS, since it is a) not securing any …
=> Remove Oracle from Pangolin

defi/src/protocols/data.ts
Mean finance is using API3 as the [primary oracle on Polygon](https://medium.com/api3/mean-finance-partners-with-api3-for-first-party-data-feed-solution-d514d5e9d28a), This PR adjusts the oracle used on all the chains Mean finance is operating on
=> Update Mean finance oracles per chain basis and add API3

defi/src/protocols/data.ts
Reverts DefiLlama/defillama-server#3315
This is more of a question. The initial PR links to a repo where Redstone shows a [custom oracle implemention](https://github.com/redstone-finance/redstone-oracles-monorepo/tree/main/packages/on-chain-relayer/contracts/custom-integrations/mento) **in their own github orga**.
When checking for the oracle implementation on e.g. Mento (which you can find [here](https://github.com/mento-protocol/mento-core/blob/develop/contracts/oracles/SortedOracles.sol)) there is no mention of redstone anywhere. 
Additionally i've took the liberty to ask around in their respective discords (both Moola and Mento alike) and got this answer: 
There is also no mention of 'Redstone' anywhere in the Mento docs [here](https://docs.mento.org/mento/protocol-concepts/oracles). …
=> Revert "added redstone oracles to mento, moola, and pangolin"

defi/src/protocols/data.ts
Kyberswap doesn't utilize Oracles directly for their DEX. Which i also confirmed on their discord: 
I've also checked their Chainlink announcement here: 
https://blog.kyber.network/kyberswap-integrates-chainlink-price-feeds-to-facilitate-its-defi-and-dao-operations-72c60bdc01ae
This clearly states that Chainlink oracles are merely used to convert wbtc & eth fees into KNC. This doesn't secure any value on the DEX itself. 
Band doesn't even pop up in their docs anymore and it also doesn't matter since oracles are not utilized to secure TVL in general by Kyberswap.
=> Remove Oracles from Kyberswap Classic

defi/src/protocols/data2.ts
Kyberswap doesn't utilize Oracles directly for their DEX. Which i also confirmed on their discord: 
I've also checked their Chainlink announcement here: 
https://blog.kyber.network/kyberswap-integrates-chainlink-price-feeds-to-facilitate-its-defi-and-dao-operations-72c60bdc01ae
This clearly states that Chainlink oracles are merely used to convert wbtc & eth fees into KNC. This doesn't secure any value on the DEX itself. 
Band doesn't even pop up in their docs anymore and it also doesn't matter since oracles are not utilized to secure TVL in general by Kyberswap.
=> Remove Oracles from Kyberswap Elastic

defi/src/protocols/data.ts, defi/src/protocols/data2.ts
There was an [announcement ](https://medium.com/@sarah_austin/kava-integrates-chainlink-as-its-official-oracle-network-to-bring-defi-to-cosmos-e31c2c2e929)in 2020 that Chainlink will support Kava. 
However, the [Chainlink Docs](https://docs.chain.link/data-feeds/price-feeds/addresses) still don't list Kava as a supported network. 
Out of interest i've asked around in the Kava discord and it turns out that this integration never materialized. 
There are no Chainlink nodes on Kava, hence all TVS attributed to Chainlink is false.
=> Remove Chainlink from Kava Ecosystem Projects

defi/src/protocols/data.ts
This one was a bit tougher to crack. So Dyfn is effectively just a univ2 fork that utilizes no oracles. 
They additionally have a prediction market that utilizes oracles. Docs to that can be found [here](https://docs.dfyn.network/prediction-markets/prediction-markets-faqs#how-is-the-price-of-an-asset-determined). 
For some reason the entire TVL of the DEX here was attributed towards these oracles even tough it's only the prediciton market that ulitizes them. 
If you check the prediction market [contract](https://polygonscan.com/address/0x150B4fD25c7c0c65301e86B599822f2feeCC29E7#code), it has last been used over 550 days ago and barely has 1.5k TVL in it. 
This follows the typical scheme of oracle projects simply creating PRs to ramp up their TVS numbers. 
I'd suggest ignoring the …
=> Remove Oracles from Dyfn Network

defi/src/protocols/data3.ts
Binance Oracle now supports Kinza Finance. Please find the official announcement here https://twitter.com/kinzafinance/status/1684248232644481025?s=20
=> Adding Binance Oracle to Kinza Finance

coins/src/adapters/tokenMapping.json
This PR will add:
SOMM - Sommelier Finance
USDC - Circle Native USDC on Cosmos
SHD - Shade Protocol on Secret Network
As IBC denoms from Kujira
=> Add SOMM, Native USDC and SHD as Kujira IBC Denoms

defi/src/protocols/data2.ts
Wrongly attributed TVS to DIA. 
It's only used on Arbitrum. Check the snapshot proposal. 
https://snapshot.silo.finance/#/proposal/0xa6b5051b23999570bfefdacd5ae2a497a9d9e492b9f8126e5b6568b5962ed71a
=> update oracles for silo finance

coins/src/adapters/index.ts, coins/src/adapters/yield/mux/index.ts
MUX Leveraged Trading Protocol - A decentralized leveraged trading protocol that offers zero price impact trading, up to 100x leverage, no counterparty risks for traders and an optimized on-chain trading experience. Traders will trade against the MUX native pool (MUXLP pool) on the Leveraged Trading Protocol.
The universal liquidity pool on MUX holds a portfolio of assets, and each asset has a targeted weight in the pool. Pooled assets will be utilized for MUX margin trading to earn fees.
Users can provide liquidity by buying MUXLP with assets allowed by the portfolio. MUXLP tokens are minted when buy orders are filled and burnt when sold. The MUXLP token price is calculated by dividing the MUXLP pool value by the total MUXLP supply. After buying MUXLP tokens, users can stake the tokens …
=> Add MUXLP to coins API

coins/src/adapters/tokenMapping.json
I think the original address is wrong (it's not for scroll, but mainnet). Take a look at the json file
https://scroll-tech.github.io/token-list/scroll.tokenlist.json
=> Update tokenMapping.json correctly

defi/src/protocols/data2.ts
Add "Umbrella Network" as oracle for WeFi protocol.
The partnership was announced in this tweet: https://twitter.com/UmbNetwork/status/1712466650547806274
=> Add Umbrella Network as oracle for WeFi

defi/src/protocols/data3.ts
gm,
we would like to request adding RedStone as an Oracle for Premia
Materials:
https://twitter.com/PremiaFinance/status/1703773649847693581 
https://docs.premia.blue/the-premia-protocol/concepts/oracles 
Thanks
Matt
=> Add RedStone Oracles to Premia

coins/src/adapters/index.ts, coins/src/adapters/markets/curve/contracts.json, coins/src/adapters/markets/curve/index.ts, coins/src/adapters/yield/misc4626/tokens.json
Added support for MaigcCurveLP on Kava. Also added price for Curve on Kava as MagicCurveLP is an ERC4626 of a Curve pool (does this need to happen in a separate PR?). Untested as I do not know how, so may not work.
=> feat(abracadabra): Add pricing for MagicCurveLP on Kava

coins/src/adapters/tokenMapping_added.json
fix: token(0x6Fae4D9935E2fcb11fC79a64e917fb2BF14DaFaa) wrong coingecko API id
https://www.coingecko.com/en/coins/celestia
https://www.coingecko.com/en/coins/tia
=> fix: wrong manta TIA API id

defi/src/protocols/data2.ts
Gm, there was a previous PR i did [here](https://github.com/DefiLlama/defillama-server/pull/4422) where i said to remove DIA as an oracle for Silo on the Ethereum Markets, as governance only approved Arbitrum markets.
Since then i did a bit more digging into what Silo actually uses on an asset by asset basis. 
Each pool is in effect isolated, so whatever oracles you use, you merely "secure" those pools. 
There are 60M in TVL for Silo on the Arbitrum markets of which all is attributed to DIA. 
However, if you investiage on the [Silo Dahsboard ](https://app.silo.finance/) which pools are actually secured by DIA, we come to a total of 2.68M (4.46% of the entire arbitrum TVL).
The following markets are secured by DIA:
[Silo ](https://app.silo.finance/silo/0xae1Eb69e880670Ca47C50C9CE712eC2B48Fa …
=> Remove DIA from Silo Finance [Arbitrum] entirely

defi/src/protocols/data.ts
I spoke with the team at Idle, and here is a screenshot of them declaring that they do not use chainlink as an oracle.
=> removed chainlink from Idle

defi/src/protocols/data.ts, defi/src/protocols/data3.ts
gm llama sirs
requesting your review to add KTX and dForce as Pyth oracle users, on Mantle and Conflux respectively
links attached:
https://docs.ktx.finance/background
https://docs.dforce.network/faq-and-guides/faq#how-do-you-source-price-feeds
thank you
=> add dforce and ktx

defi/src/protocols/data3.ts, defi/src/protocols/parentProtocols.ts
1. Change the token address for v1 back to the v1 token address. This can be confirmed [here](https://docs.juicebox.money/dao/jbx/).
2. Update the description for v2/v3 to match the description on [Juicebox's website](https://juicebox.money/).
3. Update audit info. "Juicebox v3" was a re-deploy of Juicebox v2, incorporating feedback from the audits which took place after v2 had been launched. The buyback delegate audit is relevant as well – this component is used by [JuiceboxDAO's project](https://juicebox.money/@juicebox), which collects fees from all v3 projects. Please tag `filipvv` on Discord if you'd like any further clarification.
Thank you again for your help.
=> Update Juicebox Info

defi/src/protocols/data3.ts
Hey Llamas. 
Metavault Perps v2 is utilizing a double oracle approach with pulling prices from Pyth and checking them against API3. 
Traders hence can only open a position if Pyth & API3 are within a certain range from each other.
https://x.com/MetavaultTRADE/status/1734226620591043063?s=20
Thank you!
=> add api3 user

defi/src/protocols/data3.ts
Reason: more and more contracts forked from Uniswap v2 & Pancakeswap than Syncswap. Additionally, Syncswap is also forked from Uniswap.
=> fixed forkedFrom

defi/src/protocols/data.ts
gm 
requesting your review to add Pyth back to Solend
not sure why Solend was taken out from Pyth as it's the primary oracle for the main pools
thank you
=> add solend to Pyth

defi/src/protocols/data2.ts
This is a PR to remove the Liquidity Product of the Project Kamino from Pyth TVS. 
[According to their documentation,](https://docs.kamino.finance/products/liquidity) using Kamino Liquidtiy, you can pool assets and receive kTokens for them that are in effect simply LP tokens (no oracle involvement, also not found in their documentation). 
These tokens are then useable in their lending product [Kamino Lend](https://defillama.com/protocol/kamino-lend). 
Not only, is the TVS being double counted here, as Kamino Liquidity kTokens are all TVL for Kamino Liquidity and effectively nearly all TVL in Kamino Lend (because the kTokens are simply deposited there), but i couldn't find any evidence for Kamino Liquidity actually utilizing oracles for the creation of these kTokens.
The only thing that …
=> remove "Kamino Liquidity" from Pyth TVS

defi/src/protocols/data2.ts
Well, Chainlink doesn't operate on Cardano.
Should be simple enough.
=> Remove Indigo from Chainlink TVS

coins/src/adapters/tokenMapping.json
Added support for following assets; and correct decimals for xcvDOT.
xcBNC, xcLDOT, xcZTG, SOL, & xcCFG
=> coins: track xcBNC, xcLDOT, xcZTG, SOL, & xcCFG

defi/src/protocols/data3.ts
it's me again. did some digging into this one. 
They're creating isolated lending markets for each LSD and allow you to mint GRAI against it. 
Claim to be using Redstone & Chainlink and upon further questioning revealed that Redstone is only used for ETHx, swETH and weETH. 
Those assets are only available on mainnet, hence Redstone can only be used on mainnet in addition to Chainlink.
I split the oracles per chain for that reason. 
Theoretically Redstone would need to be removed entirely, but i'll let you make that call since i don't want to rustle even more jimmies. Since each LSD is isolated a redstone misreport on a single one can't impact the entire TVL on ETH. 
There is a total of 37M of TVL on ETH, of which Redstone secures 10.6M (weETH), 2.66M (swETH) and 4.5k (ETHx), which amounts …
=> update gravita oracle

defi/src/protocols/data3.ts
[Lendle.xyz](https://www.lendle.xyz) has integrated API3 oracles for their mETH market.
- Docs: https://docs.lendle.xyz/using-the-lendle-application/markets/borrow/liquidations-and-flashloans#oracles
- Announcement: https://twitter.com/API3ECO/status/1737473083336728910
mETH is currently the biggest market on lendle securing over 2.4 million in value and containing most of the protocols TVL. In addition it has the highest APR on the platform compared to other assets
as such API3 is crucial in its operation
=> add api3 oracle to lendle

coins/src/adapters/yield/mean-finance/index.ts
We found the issue with why BNB chain was failing. I'm assuming that using `bnb` worked at some point, but then it stopped working
=> fix: use correct name for bsc

coins/src/adapters/tokenMapping.json
This change adds hyUSD (minted [here](https://register.app/#/overview?token=0xCc7FF230365bD730eE4B352cC2492CEdAC49383e&chainId=8453)) to DefiLlama's coin price API
=> Update tokenMapping for hyUSD (Base)

defi/src/protocols/data2.ts
To obtain the price of assets like Bitcoin and Ethereum, we leverage PYTH's on-chain oracle. We also use this price feed to start and end rounds.
=> Oracle details updated for Netxer finance(Previously Bhvaish Finance)

defi/src/protocols/data3.ts
Init capital uses API3 feeds for all of their money markets on Mantle : https://init-capital.gitbook.io/init-capital/borrowing/assets-list#stable-assets
In case its not clear, Init is a decentralized lending and borrowing protocol similar to AAVE and Compund but with the ability for other dAPPs to tap into the borrowing and lending side using "Hooks" . As with any lending and borrowing protocol the TVL is secured by Oracles for things like liquidations and API3 is oracle used by init as stated in their docs
For Mintrest there was a typo, Mintrest is not live on manta, it is live on Mantle :)
=> Add API3 Oracle to Init Capital

defi/src/protocols/data3.ts
Remove "Forked from Uniswap V2", because our protocol has different interface than Uniswap V2.
=> Update VirtuSwap metadata

defi/src/protocols/data3.ts
We updated the oracle provider for Interest Protocol on Sui as we use them to secure our protocol.
Ann here: https://twitter.com/interest_dinero/status/1756237453910835644
=> feat: add pyth network to interest protocol sui

defi/src/protocols/data3.ts
Similar to kinetix dervis (v1), kinetix dervis v2 are powered by Pyth & API3. 
Tweet can be found here: https://x.com/KinetixFi/status/1755722584119750867?s=20
=> update oracles for kinetix derivs v2

defi/src/protocols/data3.ts
We just added API3 as the oracle provider for Tropykus zkEVM
=> Added API3 as an oracle for Tropykus zkEVM

defi/src/protocols/data3.ts
The currently used gecko-id for Harbor Market is incorrectly set to harbor-2. The correct gecko-id I'd like it to be set to is harbor-3.
=> Update Harbor Market gecko-id

defi/src/protocols/data3.ts
gm,
We kindly ask to update the oracle section for LayerBank on the Manta network. 
Links to the LayerBank docs: 
https://docs.layerbank.finance/protocol/lending/oracles
LayerBank’s Validator pointing to RedStone’s Oracle Contract: 
https://pacific-explorer.manta.network/address/0xF2C1E27A4Bf0D81Bb4A6E6e3E5DCD1DC6ED3A7fA?tab=read_contract#7dc0d1d0
=> Add RedStone to LayerBank on Manta

defi/src/protocols/data.ts
Hello, 
requesting to add RedStone as an oracle provider for Gearbox. RedStone feeds protect our leveraged CreditAccounts providing data in pull model for real-time collateral valuation.
Materials:
Our oracle usage is described in https://docs.gearbox.finance/ e.g. here https://docs.gearbox.finance/traders-and-farmers/pro-leverage-bible#where-do-price-feeds-come-from
https://twitter.com/GearboxProtocol/status/1755632665523523707
=> add redstone oracles to gearbox

defi/src/protocols/data3.ts
Gm,
We kindly ask to update Oracles for the 
1) Sturdy protocol: 
Implementation: RedStone provides all the price feeds for Sturdy on the MODE chain
Documentation/Proof: https://docs.sturdy.finance/overview/security-and-audits
2) Ionic protocol:
Implementation: RedStone provides all the price feeds for Ionic on the MODE chain
Documentation/Proof: https://doc.ionic.money/ionic-documentation/ionic-protocol/oracles#oracle-types
3) Ironclad:
Implementation: RedStone provides all the price feeds for Ironclad
Documentation/Proof: https://docs.ironclad.finance/resources/protocol-security#base-oracle-provider
For your convenience  the links to docs are also included in the data file.
=> Update oracles for Sturdy, Ionic & Ironclad

defi/src/protocols/data3.ts
Gm,
We kindly ask to update Oracles for the JuiceFinance protocol:
Implementation Details: RedStone provides all the price feeds for Juice Finance
Documentation/Proof: https://juice-finance.gitbook.io/juice-finance/juice-finance/quick-links
Announcement: https://twitter.com/redstone_defi/status/1767219012147311017
=> Add RedStone as an Oracle for Juice Finance

defi/src/protocols/data3.ts
Liquid FIL is pledged with the Filecoin blockchain when participating in mining, and this is the native staking mechanism on Filecoin. Users that stake FIL natively can opt-in to the Repl protocol to restake their FIL to obtain pFIL, in order to use it for additional use cases such as securing other L2s. With such a mechanism, Filecoin can lend its security to its L2s by providing pledged FIL equivalent with pFIL. If would this be more appropriate to label Repl's category as a restaking protocol in the filecoin ecosystem.
Moving forward, we also plan to integrate other DePIN liquid staking tokens into the protocol by enabling them to be restaked on Repl to earn additional rewards.
=> Update Repl category to Restaking

defi/src/protocols/data3.ts
Hi all,
requesting your review to add Pyth back to Ionic
Doc
https://doc.ionic.money/ionic-documentation/ionic-protocol/oracles#oracle-types
Oracle implementation
https://github.com/ionicprotocol/contracts/blob/development/contracts/oracles/default/PythPriceOracle.sol
Thank you
=> add Pyth to Ionic

defi/src/protocols/data3.ts
Pac Finance uses API3 for their oracle
docs: https://docs.pac.finance/security#oracle
Juice Finance uses API3 for their ETH feed which is 65% of their TVL and also fallback for their USDB feed
docs: https://juice-finance.gitbook.io/juice-finance/juice-protocol/risks#oracle-risk
=> add API3 oracle to Juice, Pac finance

defi/src/protocols/data3.ts
Gm, 
We kindly ask to update oracles for Juice Finance to RedStone. 
Implementation Details: RedStone provides price feeds for ETH & USDB (87% of TVL)
Documentation/Proof: https://juice-finance.gitbook.io/juice-finance/juice-protocol/borrowing/liquidations#oracles
=> Update oracles for Juice Finance

defi/src/protocols/data.ts
Changes include:
- removing the space in the name
- updating the description
- changed category to RWA because carbon and environmental assets are RWAs (KlimaDAO now controls the BCT carbon pool)
- changed logo to new logo url from PR https://github.com/DefiLlama/icons/pull/1409
=> Update KlimaDAO information

defi/src/protocols/data.ts, defi/src/protocols/data2.ts
Recently Arrakis moved away from the `beta` website.
Trying to update the old directories the point to the right URL, so that wallets such as Rabby don't label the new one as "low popularity".
=> chore: update Arrakis urls

coins/src/adapters/tokenMapping.json, defi/src/protocols/data3.ts
Issue: https://github.com/DefiLlama/defillama-server/issues/6415
Currently, `0x05ffbcfeb50d200a0677c48a129a11245a3fc519d1d98d76882d1c9a1b19c6ed` is registered as ZENd address, but it is not the correct ZEND address. It is the class hash of that contract on Starknet, which is totally different. 
[0x00585c32b625999e6e5e78645ff8df7a9001cf5cf3eb6b80ccdd16cb64bd3a34](https://starkscan.co/contract/0x00585c32b625999e6e5e78645ff8df7a9001cf5cf3eb6b80ccdd16cb64bd3a34) is the correct token address.
So this PR changes the token address to the correct one.
=> fix: ZEND token address

coins/src/adapters/utils/erc4626.ts, coins/src/adapters/yield/mean-finance/mean-finance.ts
We realized one of the 4626 adapter tokens we supported was failing due to a problem with the underlying vault. This was causing all calls to fail, so we realized we needed to change the approach. The idea is simple though, if a token fails to report any of the properties, we will simply ignore it and return prices for the rest
I wasn't sure if it made sense to log a warning, but I can do it if you would like me to
=> fix: handle failing erc4626

defi/l2/storeToDb.ts
The Bitcoin chain page currently crashes because of a chain assets chart data table containing [null]. This fixes it by avoiding returning a null element when there is no data. A similar PR has been made on the frontend to prevent the frontend from crashing in case this happens -> https://github.com/DefiLlama/defillama-app/pull/1677
=> avoid returning an array containing a null element when there is no assets history data

defi/src/protocols/data3.ts
Juice Finance uses API3 for their primary feeds for ETH, USDB and ezETH (100% of TVL)
Documentation: https://juice-finance.gitbook.io/juice-finance/juice-protocol/borrowing/liquidations#oracles
=> update oracle for juice finance

defi/src/protocols/data3.ts
Gm,
Kindly asking to update oracles for Evaa Protocol:
Implementation Details: RedStone provides all price feeds for Evaa
Documentation/Proof: https://evaa.gitbook.io/intro/details-of-protocol/risks/protocol-risks#oracle-risk
=> Update oracle for Evaa

defi/src/protocols/data3.ts
Gm,
Kindly asking to update oracles for Merchant Moe Liquidity Book
Implementation Details: RedStone provides price feeds for assets in MM LB's vaults, including USDT (~90% of MM LB TVL)
Documentation/Proof: https://docs.merchantmoe.com/liquidity-book/vaults#h_e0c60a9c6a
=> Add RedStone to Merchant Moe Liquidity Book

coins/src/adapters/tokenMapping.json
PR to add LightLink token to coins api.
ETH: https://etherscan.io/address/0x0921799CB1d702148131024d18fCdE022129Dc73
Phoenix: https://phoenix.lightlink.io/token/0xd9d7123552fA2bEdB2348bB562576D67f6E8e96E
Coin Gecko: https://www.coingecko.com/en/coins/lightlink
=> add LL token to tokenMapping.json

defi/src/protocols/data3.ts
Gm Llamas, 
Kindly asking to update oracles for Native
Implementation Details: RedStone provides price feeds for Native on zkLink
Documentation/Proof: https://docs.native.org/aqua/smart-contracts/smart-contract-addresses
=> Add RedStone to Native

defi/src/protocols/data3.ts
Gm Llamas,
Kindly asking to update oracles for Seismic
Implementation Details: RedStone provides price feeds for Seismic to determine value of borrowed assets and collateral
Documentation/Proof: https://docs.seismic.finance/accepted-collateral-types#oracles-utilized
=> Add RedStone to Seismic

coins/src/adapters/tokenMapping.json
To correctly calculate the staking values on Base and Mode we are requesting this mapping for our native PEAS token.
After testing the correct values on our new adapter version, we'll create a PR for this to add support for these networks.
=> Add PEAS token to tokenMapping.json for Base and Mode network

coins/src/adapters/tokenMapping_added.json
Currently significant part of TON TVL is missing due to USDT has been added to the core assets but [coins api](https://coins.llama.fi/prices/current/ton:EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs) has a lack of support for USDT.
=> Added USDT on TON

defi/src/protocols/data3.ts
API3 is the primary oracle for the ETH/USD feed for Orbit Protocol which is 85% of orbit TVL.
Docs: https://book.orbitlending.io/protocol-design/price-oracle#api3
Redstone is the primary oracle for USDB feed for Orbit Protocol which is 14% of orbit TVL. 
Docs: https://book.orbitlending.io/protocol-design/price-oracle#redstone
A potential misreport of any of these oracle could cause the protocol to lose >50% TVL since this is a compoundv2 fork and the markets are not isolated
=> add API3 and Redstone to Orbit Lending 

defi/src/protocols/data3.ts
API3 is used a primary oracle in mendi markets including ezETH which is the biggest market on mendi.
docs: https://docs.mendi.finance/protocol/oracles
accepted proposal: https://gov.mendi.finance/t/mip-3-mendi-finance-to-continue-using-api3-for-ezeth-price-data-and-benefit-from-oev/59/4
Chainlink is the other primary oracle as per documentation so added them as well. 
A misreport on any of these oracles can cause > 50% the protocol TVL to be drained since this is a compoundV2 forks and markets aren't siloed.
=> add api3 oracle to mendi finance

defi/src/protocols/data3.ts
Hey Llamas,
Kindly asking to update oracles for LayerBank on BSquared and BOB and for Vivacity on Canto.
Implementation Details: LayerBank uses RedStone Price Feeds for pricing collateral on all existing markets on Bsquared, and BOB. Vivacity uses RedStone Price Feeds for pricing crypto native assets (>50% of their TVL)
Documentation/Proof: 
[LayerBank] https://docs.layerbank.finance/protocol/lending/oracles [Vivacity]
https://docs.vivacity.finance/reference/architecture#price-oracles
=> Update oracles for Vivacity and LayerBank.ts

defi/src/protocols/data3.ts
Gm,
Kindly asking to update oracles for Shoebill Finance on BSquared and BOB.
Implementation Details: Shoebill Finance integrated our feeds for major assets on these networks
Documentation/Proof: https://docs.shoebill.finance/risk/oracle
=> Update Oracles for Shoebill Finance.ts

defi/src/protocols/data3.ts
Gm,
Kindly asking to update oracles for ZeroLend on Blast, Linea and Mainnet.
Implementation Details: RedStone protects all ZeroLend's markets on Manta, Blast and also provides LRT feeds on ETH mainnet and Linea.  (>50% of Linea and mainnet TVL is in LRTs)
Documentation/Proof: https://docs.zerolend.xyz/security/oracles#using-redstone-oracles
=> Update Oracles for ZeroLend.ts

coins/src/adapters/rwa/dinari.ts
Our factory contract and order fill data can be used to compute TVL for all our assets.
This fixes current incorrect tokens and incomplete pricing information in a sustainable way going forward.
See https://github.com/DefiLlama/DefiLlama-Adapters/pull/10354
=> feat: Dinari native prices

defi/src/protocols/data3.ts
We want to add another supported chain to our info. 
Our category should be "Dexes" on the Taiko network and "Derivatives" on the Blast network
Thx for supporting
=> chore: add DTX chains info

defi/src/protocols/data3.ts
Update name "Polkadex Trade" to "Polkadex".
Update category from "Derivatives" to "Dexes"
=> Fix polkadex name and category

coins/src/adapters/rwa/kuma.ts
I also noticed that while we have the USK oracle defined here, and it seems to be writing the prices as expected, the TVL calculation sometimes doesn't seem to take them into account, leading to spikes in our DefiLlama listing. Any idea on how to prevent this from happening? Adapter code: https://github.com/DefiLlama/DefiLlama-Adapters/blob/b91efa646707c6653227a5f5677b456e0447ee2c/projects/kuma/index.js
Example of the issue happening for USK on Ethereum (but same applies for the other USKs so my hunch is something wrong with the oracle / price calculation - but I wasn't able to reproduce the problem). Even right now it's not counting USK on Ethereum or Linea, just EGK on Ethereum and FRK on Polygon.
Edit: just ran it again to confirm total numbers, and now in my instance it did pull the …
=> Add USK on Telos

defi/src/protocols/data3.ts
This one seemed like a no-brainer but apparently not. 
Naturally i've assumed (similar to others) that the MakerDAO AAVE Fork uses the MakerDAO oracles under the hood.
This is mostly untrue and in most instances not even documented. 
These docs say nothing about any oracle they use: https://docs.spark.fi/
Then you dig into their forum and realize, that their Gnosis Chain deployment relies just on Chainlink: https://forum.makerdao.com/t/spark-lend-on-gnosis/21304
Then you dig into some of the mainnet reconfigurations of a major asset like e.g. wBTC and realize that this also uses Chainlink under the hood. https://forum.makerdao.com/t/spark-parameter-change-mainnet-reactivate-wbtc/22556
As far as my forum search has lead me Spark utilizes Chronicle nearly nowhere. 
Chronicle as a project …
=> Remove Chronicle from Spark

defi/src/protocols/data3.ts
gm
requesting your review to add Pyth users
Flat Money
https://docs.flat.money/pyth-network-price-oracle 
Superposition
for context, Superposition is powered by Concordia, which uses Pyth for its pricing engine
https://docs.concordia.systems/platform-spec/pricing-engine 
Also there seems to be an issue with Zerolend. It's using Pyth for zkSync but can't seem to find it on the Pyth page https://defillama.com/oracles/Pyth
Could you take a look please?
Thank you very much
=> add new pyth users

defi/src/protocols/data.ts
KlimaDAO was in the wrong category. Environmental commodities like carbon credits are real world assets.
=> fixed KlimaDAO in wrong category

coins/src/adapters/moneyMarkets/aave/index.ts
in https://github.com/DefiLlama/defillama-server/pull/7224/commits/a0aa59127be046e7eaa94c411fe0934ec7432eb8 i replaced the package imports with raw addresses and apparently did a copy paste error for arbitrum(currently it's the oracle address, although should be the factory address) :/
=> fix: copy paste error

coins/src/adapters/moneyMarkets/aave/aave.ts
I cannot manage to run the test locally atm, so sadly there's no option for me to test if it actually works
=> fix: use lowercase for db lookup etc

coins/src/adapters/markets/bitcow.ts
Add stBTC-WBTC Pool to bitcow adapter.
- stBTC-WBTC Pool: https://www.btrscan.com/address/0xcc2daecb9a96eedd2d48259d664d5d48791a7f79
- stBTC-WBTC LP Token https://www.btrscan.com/address/0xb88a54ebbda8edbc1c2816ace1dc2b7c6715972d
=> add: stBTC-WBTC pool to bitcow adapter

coins/src/adapters/tokenMapping.json
- Add SolvBTC-ENA, which pegs to SolvBTC
---
[**SolvBTC-ENA Intro**](https://solvprotocol.medium.com/bitcoin-meets-defi-a-deep-dive-into-the-solvbtc-ethena-vault-43abc8597a47)
SolvBTC.ena serves as a liquid yield token, integrated with various DeFi protocols, offering maximum flexibility and accessibility for a thriving BTCFi ecosystem. Key integrations include:
- DEXs: Provides SolvBTC.ena holders with instant liquidity and access to high-quality yields without requiring KYC.
- Lending Protocols: Allows SolvBTC.ena holders to lend their tokens, earning extra yield while enabling borrowers to access leveraged yield positions.
- Yield-Trading Protocols: Enables users to trade the future yields of SolvBTC.ena, manage yield exposure fluctuations, and optimize returns.
Through these …
=> Add: SolvBTC-ENA on BSC

defi/src/protocols/data3.ts
Adding Pyth as an oracle source for vega protocol.
For info this is a link to the documentation: https://docs.vega.xyz/mainnet/tutorials/using-data-sources#using-a-pyth-price-feed
=> Add Vega Protocol as a Pyth oracle user

defi/src/protocols/data3.ts
Changes the TLX Finance category from Synthetics to Derivatives, as this is the more appropriate category.
=> TLX Finance category changed from Synthetics to Derivatives

coins/src/adapters/tokenMapping_added.json
The stablecoin section is showing incorrect data for the Celo chain. 
Adding 5 stablecoin addresses that collectively have a TVL of around $240M.
USDC contract address taken from:
https://tether.to/en/supported-protocols/
Tether contract address taken from:
https://tether.to/en/supported-protocols/
Celo stablecoin contract addresses taken from:
https://docs.celo.org/token-addresses
=> Adding Celo stablecoin addresses

defi/src/utils/normalizeChain.ts
Adds Superchain category to relevant chains. Sourced from the[ public tracker](https://docs.google.com/spreadsheets/d/1CRXo9YcP9fzJZxmKmEbNcPkZebgpUBMKo63HUhDKy2U/edit?gid=0#gid=0) (in the interim until the superchain-registry is oeprational)
Other changes:
- Recategorize Ham as Superchain ([Source](https://medium.com/@hamlabs/announcing-ham-chain-5597a1082769))
- Update Zora's Twitter Account ([Source](https://x.com/zora))
- Added Chain IDs when missing
Other open qustions:
- Some chains didn't have "Rollup" as a category, I tried to not change this, but wondering what the definition is (i.e. does it require Ethereum L1 DA?)
=> Add Superchain Category

coins/src/adapters/tokenMapping.json
`CVX1` is a token that can be always, at a 1:1 ratio : 
- Minted by exchanging `CVX`
- Burnt in exchange of `CVX`
The underlying price of `CVX1` is so the price of `CVX`.
CVX1 is a product of Convergence Finance : https://app.cvg.finance/
If needed, here are more informations about `CVX1`=> https://medium.com/cvgfinance/focus-on-cvgcvx-9db67f9bbc32
=> Add CVX1 token to tokenMapping.json

defi/src/protocols/data3.ts
Hey Llamas,
Kindly asking to update oracles for Yei Finance on Sei and Segment Finance on BOB.
Implementation Details: Yei Finance uses RedStone USDT,USDC feeds as primary which is >50% of their TVL.
Segment Finance uses RedStone WBTC, ETH, USDC, USDT, STONE feeds on BOB as primary which is >50% of their TVL.
[Yei Finance] https://docs.yei.finance/welcome-to-yei/security-and-risk/oracles-and-data-feeds
[Segment Finance] https://docs.segment.finance/protocol/price-feeds
=> Udate Oracles for Yei Finance and Segment Finance

defi/src/protocols/data3.ts
Hey Llamas,
Kindly asking to update oracles for Yei Finance on Sei and Bitlen Finance
Implementation Details: Yei Finance uses RedStone USDT, USDC feeds as primary which is >50% of their TVL. This info is clearly stated in their docs ("RedStone USDT and USDC push feeds are used as primary oracle for these assets.") and confirmed by their team.
Bitten Finance uses RedStone as the primary solution for asset pricing.
[Yei Finance] https://docs.yei.finance/welcome-to-yei/security-and-risk/oracles-and-data-feeds
[Bitlen Finance] https://docs.bitlen.io/borrowing/oracle
=> Update oracles for Yei Finance and Bitlen Finance.ts

defi/src/governance/icp/sns.ts
Currently, it only fetches 5 sns as it's the default value if no param is provided, we should fetch all which can be done using the param limit = 100.
=> Fetch all SNS

defi/src/utils/normalizeChain.ts
Updated Klaytn details to Kaia.
Details:
Klaytn along with Finschia is now rebranded to Kaia. The Kaia Blockchain is a hard fork of Klaytn. Please refer to this https://klaytn.foundation/say-hello-to-kaia/ and https://kaia.io/ for more details.
=> Updated Kaia details

defi/src/protocols/data3.ts
Hey Llamas,
Kindly asking to update oracles for Skate Fi on mantle and Native Lend.
Implementation Details: Skate Fi uses RedStone feeds on Mantle for asset pricing.
Native Lend uses RedStone as the primary solution for asset pricing.
[Native Lend] https://docs.native.org/native-dev/getting-started/lend#:~:text=worry%20about%20inventory.-,Oracles,-Native%20uses%20RedStone
[SkateFi] https://docs.skatechain.org/skate-fi/vertex#oracles
=> Update oracles for Native Lend and Skate Fi

defi/src/protocols/data3.ts
Hey Llamas,
Kindly asking to update oracles for Yei Finance on Sei.
Implementation Details: Yei Finance switched to RedStone push feeds as the primary solution for asset pricing on all liquidity pools last week.
https://docs.yei.finance/welcome-to-yei/security-and-risk/oracles-and-data-feeds#redstone
=> Update oracles for Yei Finance.ts

defi/src/protocols/data3.ts
Hey Llamas,
Kindly asking to update oracles for LayerBank and SumerMoney on zkLink.
Implementation Details: LayerBank uses RedStone feeds on zkLink for asset pricing.
SumerMoney uses RedStone feeds on zkLink for asset pricing.
[LayerBank] https://docs.layerbank.finance/protocol/lending/oracles 
[SumerMoney] https://docs.sumer.money/developers/price-feeds/redstone-price-feeds-on-zklink-nova
=> Update oracles for LayerBank and SumerMoney on zkLink.ts

defi/src/protocols/data3.ts
Oracle Provider(s): Specify the oracle(s) used: adding Chronicle Oracles for Spark.fi
Implementation Details: Briefly describe how the oracle is integrated into your project:
- Spark.fi Oracle Upgrade for ETH, wstETH, rETH and weETH markets to use Aggor 
- Spark.fi  integration for Chronicle's LIDO_LST/2DAYS Oracle
Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
- [LIDO_LST/2DAYS](https://etherscan.io/address/0xaBc99f366D2bE1f4e5b8DFC0F561a751dd836246#readContract)
- [Aggor](https://etherscan.io/address/0xf07ca0e66A798547E4CB3899EC592e1E99Ef6Cb3#code)
- [Aggor2](https://etherscan.io/address/0x00480CD3ed33de45555410BA71b2F932A14b1Cf2#code)
- [Aggor3](https://etherscan.io/address/0x69115a2826Eb47FE9DFD1d5CA8D8642697c8b68A#code)
- …
=> Add Chronicle for Spark

defi/src/protocols/data3.ts
Project name and Defi category was described properly from this PR.
https://github.com/DefiLlama/DefiLlama-Adapters/pull/11343
=> fix: update defi category and project name into correct one for double

defi/src/protocols/data3.ts
Hey Llamas,
Kindly asking to update oracles for ZeroLend on Zircuit.
Implementation Details:
ZeroLend uses RedStone Oracles as the primary solution for asset pricing on Zircuit.
https://docs.zerolend.xyz/security/oracles#using-redstone-oracles
=> Update Oracle for ZeroLend on Zircuit.ts

coins/src/adapters/tokenMapping.json
This PR was created to update the USDC Token contract address on the Bitlayer chain.
To comply with Circle's protocol requirements and ensure the stability and compliance of the Bitlayer ecosystem, Bitlayer has renamed the USDC Token. For details, please refer to: https://blog.bitlayer.org/USDC_._e_to_USDC_Conversion_Guide
As a result, we have updated the code to modify the contract address of the USDC Token. Please review and merge the changes. Thank you!
=> new Bitlayer USDC address

defi/src/protocols/data2.ts
Proof：
https://medium.com/apx-finance/apx-v2-integrates-with-pyth-network-for-enhanced-real-time-price-accuracy-and-security-31d0ba5fb2b0
This says that Pyth is a primary oracle, chainlink is backup oracle.You can also check with pyth, this information is visible in the contract
You can also check this: https://www.apollox.finance/en/futures/v2/BTCUSD (Pyth logo on APX website)
btw, you can also check with Pyth team
Thanks very much!
=> feat: update APX Finance oracles

defi/src/protocols/data3.ts
gm llama sirs
adding new Pyth oracle users:
- Modemax - https://docs.modemax.io/overview/terminology#oracle-pricing
- Amulet v2 - https://docs.amulet.org/documentation/product/yield-with-built-in-protection/oracle-integration#functionality
- Injera - 
https://docs.injera.io/injera-money-market/oracles
- Jellyverse - https://docs.jellyverse.org/protocol-library/jassets-by-blkswn/pricefeed-and-oracle
- Joule - https://docs.joule.finance/docs/money-market/oracle
- Kwenta - https://docs.joule.finance/docs/money-market/oracle
- Lumen Money - https://docs.lumen.money/protocol/security
- Primex - https://docs.primex.finance/guides/what-is-primex/economic-security/oracles/pyth-network-oracle
=> add new oracle users

defi/src/protocols/data3.ts
Hey Llamas,
Kindly asking to update oracles for Cygnus and Lets Get Hai.
Implementation Details: 
Cygnus is using RedStone pull model as the primary solution for asset pricing on TON, BASE, Bsquared.
HAI is using RedStone Push model as one of its primary solutions for crypto assets pricing on Optimism.
[Cygnus] https://wiki.cygnus.finance/whitepaper/cygnus-network/how-does-cygnus-work#:~:text=Cygnus%20uses%20RedStone%20Oracles
[HAI] https://docs.letsgethai.com/detailed/intro/hai.html#redstone-oracles:~:text=friendly%20stablecoin%20system.-,RedStone%20Oracles,-HAI%20uses%20RedStone
=> Update Oracles for Cygnus and Lets Get Hai.ts

defi/src/protocols/data3.ts
- Adding Chronicle as powering M0
- M0 uses [Chronicle's RWA Oracle](https://www.m0.org/press-releases/chronicle-launches-real-world-asset-oracle-with-initial-integration-on-m-0-building-infrastructure-for-transformation-of-digital-money)
=> Update M0 description

coins/src/adapters/tokenMapping.json
Due to the API (https://coins.llama.fi/prices/current/base:0x3b86ad95859b6ab773f55f8d94b4b9d443ee931f,base:0xf469fbd2abcd6b9de8e169d128226c0fc90a012e) is missing the prices for these two tokens, our protocol’s TVL display is incorrect. Now we need to add them into the API.
=> add SolvBTC and pumpBTC price on base

defi/src/protocols/data3.ts
Hello Defillama team, I took the time to do some due diligence for this project.
According to the [docs](https://docs.puffer.fi/protocol/validator-tickets#pricing-validator-tickets) the pricing is done via Redstone oracles for the VTs but upon further investigation the current pricing mechanisms of VTs happen via a primary check of gaurdians who choose the redstone price that is posted at the 12 hour interval.
What this means is that a redstone misreport will not be accepted by the guardian because they would choose not to post it. According to the definition of [TVS](https://github.com/DefiLlama/DefiLlama-Adapters/discussions/6254)  and the question "If the oracle malfunctioned, would those assets be lost?" the answer here is no
I checked with the puffer team and they agree with my …
=> Reclassify Puffer Oracle

defi/src/protocols/data3.ts
Hello Defillama team, I took the time to do some due diligence for this project.
According to the [docs](https://docs.solv.finance/solvbtc-liquid-staking-tokens/price-oracle) Redstone oracles maintain price security for SolvBTC and its Liquid Staking Tokens (LSTs), ensuring their peg to the underlying asset prices but upon further investigation this isn't entirely correct as there are other checks notably the solv gaurdians who decide what prices land on chain 
here is a chat with the solv team:
here are the provided links: 
https://solvprotocol.medium.com/introducing-solvs-360-risk-control-safeguarding-crypto-assets-for-all-494a302a8824
https://solvprotocol.medium.com/introducing-solv-guard-enhancing-security-for-yield-vaults-c4fe66463379
specifically the solv gaurd introduces "vault …
=> Reclassify SolvBTC Oracle

coins/src/adapters/tokenMapping.json
We are now adding a mapping for $DPI
You can see that the token on Arbitrum is a bridged token from the one on Ethereum (using Chainlink's CCIP)
Source: https://indexcoop.com/blog/dpi-and-mvi-on-arbitrum-faq
_Note: not sure if this is the correct way to do this, please let me know if there is something else to do_
=> feat: add dpi arbitrum mapping

coins/src/adapters/index.ts, coins/src/adapters/other/usdrif.ts
This PR adds [USDRIF](https://rootstock.blockscout.com/token/0x3A15461d8AE0f0Fb5fA2629e9dA7D66A794a6E37) price adaptor to enable [coin prices api](https://docs.llama.fi/coin-prices-api) for [rif-us-dollar](https://defillama.com/stablecoin/rif-us-dollar)
Defillama page: https://defillama.com/stablecoin/rif-us-dollar
USDRIF: https://rootstock.blockscout.com/token/0x3A15461d8AE0f0Fb5fA2629e9dA7D66A794a6E37
Because coingecko has not enabled price for: https://www.coingecko.com/en/coins/rif-us-dollar
The purpose of this adaptor is to enable price for USDRIF in the prices api at: https://stablecoins.llama.fi/stablecoins?includePrices=true
Currently the price field is coming as null
Response from: https://stablecoins.llama.fi/stablecoins?includePrices=true
```
{
"id": "159",
"name": "RIF US …
```
=> Add `USDRIF` price adaptor

defi/src/protocols/data3.ts
gm llama sirs
adding 2 protocols under Pyth
- HLiquity, Pyth as the primary oracle https://docs.hliquity.org/deep-dive/stability-pool-and-liquidations#oracle-integration
- MORE Markets, Pyth as the primary oracle https://docs.more.markets/borrow/oracles-and-pricing
=> add protocols under pyth

coins/src/adapters/other/usdrif.ts
This PR fixes the price not showing issue at: https://defillama.com/stablecoin/rif-us-dollar
https://github.com/DefiLlama/defillama-server/pull/8492
Because the chain name `rsk` is used instead of `rootstock`.
Reference:
https://github.com/DefiLlama/peggedassets-server/blob/148b8a424ee6c7d84e12fcb21fb97e0b77e8cc13/src/peggedData/peggedData.ts#L3194
=> `USDRIF` Adaptor chain name fix

coins/src/adapters/tokenMapping.json
We would like to add lfbtc-Avalon-bsc and lfbtc-Avalon-mnt.
lfbtc-Avalon-bsc and lfbtc-Avalon-mnt are sharing the same mechanism as lfbtc-Avalon-eth. They can be minted by FBTC at 1:1 and be converted to FBTC at 1:1 as well.
Example of minting lfbtc-avalon-bsc can be found here https://bscscan.com/tx/0x5a7020ddb4316400d95ee3022971886c6f928bda012b2fc84536cf5ccff88b9d
You can see 1FBTC can mint 1 LFBTC.
=> Feat: add lfbtc on bsc and mantle

defi/src/protocols/data3.ts
Hey Llamas,
Kindly asking to update oracles for USDX Money.
Implementation Details:
RedStone stablecoin feeds are used as a cross-check during the minting /redemption process of USDX. This integration helps maintain the accuracy and security of our token's value relative to the US dollar.
Documentation/Proof: 
https://docs.usdx.money/informaiton/oracles
=> Update Oracles for USDX Money.ts

coins/src/adapters/tokenMapping.json
Add price data for USDa and sUSDa on Taiko, Zircuit and ZKsync. 
Token | Network | Contract Address
-- | -- | --
USDa | ZIRCUIT | https://explorer.zircuit.com/address/0xff12470a969Dd362EB6595FFB44C82c959Fe9ACc | https://safe.zircuit.com/home?safe=zircuit-mainnet:0x8773c75C83d497135CEf197Bd862930A04DA77FF
USDa | TAIKO | https://taikoscan.io/address/0xff12470a969dd362eb6595ffb44c82c959fe9acc | https://safe.taiko.xyz/home?safe=tko-mainnet:0x8773c75C83d497135CEf197Bd862930A04DA77FF
USDa | ZKSYNC | https://explorer.zksync.io/address/0xB8d7d88D042880aE87Bb61DE2dFFF8441768766D#transactions | https://app.safe.global/home?safe=zksync:0x1026b239E1BBC4719f7834cBCaBb461D5B8a3Edd
Token | Network | Contract Address
-- | -- | --
sUSDa | ZIRCUIT | …
=> Feat: add price for USDa and sUSDa on Taiko, Zircuit and ZKsync

defi/src/protocols/data3.ts
eOracle was added as a primary oracle on mendi finance for the weETH and WETH markets.
docs: https://docs.mendi.finance/protocol/oracles
proposal: https://gov.mendi.finance/t/mip-9-integrating-eoracle-to-the-mendi-protocol-on-the-weth-and-weeth-markets/237
snapshot: https://snapshot.box/#/s:mendifinance.eth/proposal/0x63c5a914ba319526f1f21b1b6dec8aab32703f29f214132bf489361ab7b0f836
A misreport by eOracle can cause > 50% the protocol TVL to be drained since this is a compoundV2 forks and markets aren't siloed.
=> Add eOracle to mendi finance

defi/src/protocols/data3.ts
Yei finance have updated their oracle to use API3 as the primary oracle for all their markets.
Proof in documentation: 
https://docs.yei.finance/welcome-to-yei/security-and-risk/oracles-and-data-feeds#multi-oracle-strategy
Quote from documentation:
> We choose API3 as our primary oracle for providing the main data source, while additional oracles offer supplementary validation.
How to verify:
Head over to https://app.yei.finance/ and click on `details` of any of the market. Then click on the hyperlink next to the oracle price, this will take you to the block explorer. For example, this is the link to the SEI/USD oracle hyperlink: 
https://seitrace.com/address/0x241B320946Caa015324C9b614D077B4619a4d3d3?chain=pacific-1
go to Contracts -> Read Contracts . Call the `getPrice` function and …
=> update yei finance oracle

defi/src/protocols/data3.ts
Protocol: GMX V2
Oracle Provider(s): Edge
Implementation Details: Real-time automated on-chain risk parameter updates via Edge Risk Oracles
Documentation/Proof: https://x.com/GMX_IO/status/1866794916392874021 https://gov.gmx.io/t/implementation-of-chaos-labs-risk-oracles/3861
=> Add Edge to GMX V2 Oracle list

coins/src/adapters/tokenMapping.json
We are adding a mapping for wstETH on BNB. 
Reference: https://help.lido.fi/en/articles/9739043-bridging-wsteth-to-bnb-chain
=> feat: add bnb wsteth mapping

coins/src/adapters/tokenMapping.json
This PR intends to add IBC tokens available on the Pryzm chain, in order to be used in TVL calculation for Pryzm Protocol. The respective PR on the adapters repo is https://github.com/DefiLlama/DefiLlama-Adapters/pull/12872
=> Add token mappings for IBC tokens on Pryzm

defi/src/protocols/data3.ts
gm llama sirs
adding Tren that uses both Pyth and Chainlink, as well as Neutral Trade that uses Pyth
Tren
https://docs.tren.finance/protocol/asset-risk/oracle-risk
Neutral Trade
https://docs.neutral.trade/additional-info/pyth-oracles
thank you
=> add pyth to tren + neutral trade

defi/src/protocols/data3.ts
Updated the Carrot protocol to list Switchboard as an oracle.
It is specific to Solana.
The oracle feed is here: https://ondemand.switchboard.xyz/solana/mainnet/feed/GQbKvThYgyvdp8T8MoE8KKD2NngXumQ8mDkCLxmhvJKm
=> add switchboard oracle to Carrot protocol 

defi/src/protocols/data3.ts
Dear Llamas,
We submit a PR adding RedStone as an Oracle for Tempest.
RedStone is securing both the Deposit and Withdrawal modules.
Link to Docs -> https://tempestfinance.gitbook.io/tempest-finance-docs/introduction/faq
=> chore (Tempest Finance): Add RedStone as oracle

defi/src/api2/cron-task/dimensions.ts, defi/src/api2/routes/dimensions.ts
Update protocol metadata to replace `siblingProtocols` with `linkedProtocols` for improved clarity and consistency.
=> Refactor protocol metadata keys from siblingProtocols to linkedProtocols

defi/src/protocols/data4.ts
We have decided to attach audit reports once our repositories are ready to be open-sourced. For now, we will update the audits to 0.
=> Update O.LAB metadata

defi/src/utils/normalizeChain.ts
Add Superchain tag to Swell, Soneium, Derive - all 3 appear in the Superchain Registry: https://github.com/ethereum-optimism/superchain-registry/tree/main/superchain/configs/mainnet
=> Add Superchain Tag to 3 Chains

defi/src/protocols/data3.ts
Elara uses eOracle on their main market, which is Compound V2 fork.
Docs can be found here https://learn.elara.finance/protocol/contract-addresses
To verify the oracle contract being used by the unitroller you can make a cast call as follows
`cast call 0x695aCEf58D1a10Cf13CBb4bbB2dfB7eDDd89B296 "oracle()" -r https://zircuit-mainnet.drpc.org/`
The price feeds on this oracle contract were updated on this transaction https://explorer.zircuit.com/tx/0x945a2a2a0ea44b62d57796b993ad242610b834eeed9c5b680d77dfdae84bd0ac
eOracle's zircuit price feeds can be found here https://docs.eoracle.io/docs/eoracle-price-feeds/feed-addresses/zircuit
=> Add eOracle as the oracle for Elara

defi/src/protocols/data3.ts, defi/src/protocols/data4.ts
gm llama sirs,
adding Catton and Resolv that have been leveraging Pyth oracle
Catton
https://x.com/Cattontw/status/1862096754847650156
Resolv
Resolv is currently using Pyth for both its USR and wstUSR, and the only oracle used for minting USR and RLP
https://docs.resolv.xyz/litepaper/for-developers/smart-contracts
https://docs.resolv.xyz/litepaper/for-developers/token-supply-operations/usr
https://docs.resolv.xyz/litepaper/for-developers/token-supply-operations/rlp
thank you
=> add catton and resolv to pyth

coins/src/adapters/yield/balancer4626.ts
To make sure erc4626 tokens are priced correctly on Sonic and added to Beets TVL.
=> add the beets balancer v3 deployment on sonic for pricing

defi/src/protocols/data4.ts
Ethos Markets went in yesterday; was missing smart contract audits. See: https://github.com/DefiLlama/DefiLlama-Adapters/pull/13302
=> Ethos markets smart contract audits

defi/src/api2/utils/craftParentProtocolV2.ts
order of otherProtocols is different in parent protocol https://api.llama.fi/updatedProtocol/stakestone when compare to child protocol https://api.llama.fi/updatedProtocol/stonebtc
=> fix otherProtocols order in parent protocol api

defi/src/constants/chainsByOracle.ts
Add Plume and Corn Maizenet as chains for Chronicle
- https://docs.plumenetwork.xyz/plume/nexus-data-highway/overview#oracle-partners-powering-the-nexus
- https://docs.usecorn.com/docs/developers/Infrastructure/Oracles
=> Add Plume and Corn Maizenet

defi/src/protocols/data3.ts
Spark is integrating Redstone oracles in its next spell update going live Monday, Feb 10, 2025.
RedStone oracles are integrated into the Aggor (aggregated oracle) used by Spark, for the following assets:
ETH/USD:
- WETH
- wstETH (with exchange rate provider)
- weETH (with exchange rate provider)
- rETH (with exchange rate provider)
BTC/USD:
- cbBTC
Proof:
- https://github.com/marsfoundation/spark-spells/pull/80/files#diff-0fd45385ef094b8973c5b4a1d3af9e5a8e93ab775462c494faf15bdcf4e9f37d
- https://github.com/marsfoundation/spark-spells/pull/80/files#diff-0628c3ab1637c1629905d16a817b74263f1c220c9ea476e244337481cbfc53ce
Excerpt from spell description:
| description | value before | value after |
| --- | --- | --- |
| oracle | [0xf07ca0e66A798547E4CB3899EC592e1E99Ef6Cb3](https://etherscan.io/ad …
=> Add Redstone to Spark.fi oracle data

defi/src/api2/cache/index.ts, defi/src/api2/utils/craftParentProtocolV2.ts, defi/src/api2/utils/craftProtocolV2.ts, defi/src/getYieldsConfig.ts
Introduce `otherProtocolsMap` to the cache for improved organization of child protocol names. Refactor the retrieval of child protocol names to utilize this new mapping.
=> Add otherProtocolsMap to cache and refactor child protocol name retrieval

defi/src/protocols/data4.ts
Hey Llamas,
Kindly asking to update oracles for BitFi (on all chains)
Implementation Details: BitFi is using RedStone to calulate value of assets during minting and redemption process of bfBTC. Wrong price provided by RedStone can lead to excess mint/ redemption of bfBTC and exploit of value within the protocol.
https://bitfi-2.gitbook.io/bitfi/developer/epoch-and-ratio/underlying-asset-price-variation
https://bitfi-2.gitbook.io/bitfi/developer/using-contract/unstake-bfbtc
=> Update Oracle for BitFi.ts

defi/src/protocols/data3.ts
Hey Llamas,
Kindly asking to update oracles for BitFi (on all chains)
Implementation Details: BitFi is using RedStone to calulate value of assets during minting and redemption process of bfBTC. Wrong price provided by RedStone can lead to excess mint/ redemption of bfBTC and exploit of value within the protocol.
https://bitfi-2.gitbook.io/bitfi/developer/epoch-and-ratio/underlying-asset-price-variation
https://bitfi-2.gitbook.io/bitfi/developer/using-contract/unstake-bfbtc
=> Update Oracle for BitFi BTC.ts

defi/src/protocols/data.ts, defi/src/protocols/data3.ts, defi/src/protocols/data4.ts
Few people still see the old logo. Hoping a new name for the logo fixes caches.
Corresponding icon PR: https://github.com/DefiLlama/icons/pull/2170
=> change icon url

defi/src/protocols/data3.ts
Sumer.money use eOracle for their NECT, HONEY and BERA markets on Berachain (https://app.sumer.money/?chain=80094).
Their comptroller address 0xc7fFEAa5949d50A408bD92DdB0D1EAcef3F8a3Bc
Their Pricefeed contract for NECT address https://berascan.com/address/0xc7ffeaa5949d50a408bd92ddb0d1eacef3f8a3bc#code
A cast call on the NECT price feed contract resturns the eOracle NECT price feed address 
`cast call 0xc7fFEAa5949d50A408bD92DdB0D1EAcef3F8a3Bc "chainlinkFeeds(address)" 0x1ce0a25d13ce4d52071ae7e02cf1f6606f4c79d3 --rpc-url https://rpc.berachain.com
`
You can fund eOracle berachain feeds here https://docs.eoracle.io/docs/eoracle-price-feeds/feed-addresses/berachain
Sumer money is a Compound V2 fork so misreporting on any of these oracle feeds can cause loss of all the TVL.
=> add eOracle for Sumer.money on berachain

defi/src/protocols/data3.ts
Hey Llamas,
Kindly asking to update oracles for Avalon on BSC, Sonic, Taiko.
Implementation Details: Avalon Finance (defi lending) switched to RedStone btc price feeds for main pools on BSC, Sonic, Taiko.
https://docs.avalonfinance.xyz/avalon-products/defi-lending/oracles
=> Update oracle for Avalon Finance.ts

defi/src/protocols/data.ts, defi/src/protocols/data3.ts
symbol is still "API3" not Api3
=> fix api3 rebrand errors

defi/src/adaptors/db-utils/db2.ts, defi/src/adaptors/handlers/storeAdaptorData/index.ts, defi/src/adaptors/handlers/storeAdaptorData/storeAll.ts, defi/src/api2/scripts/testDimensionsPG.ts
Change behavior of dimensions v2 adapters. 
Instead of fetching past 24 hour data, always fetch yesterday's data.
Also, if we already have data for yesterday (for both v1 & v2 adapters) we dont update the record. For adapters where we are fetching current data, run them after 19:00 UTC today, this way, we dont end up with overlapping data.
Hopefully this change will lower the stress on our system and more importantly, less bad data (less chance of common time range between two stored datapoints)
=> Fetch yesterday's data for dimensions records

defi/src/protocols/data.ts
Hey Llamas,
Kindly asking to update oracles for Venus on Unchain.
Implementation Details: Venus Protocol is using RedStone as primary Oracle provider on all Unichain pools (weth, USDC)
https://docs-v4.venus.io/risk/resilient-price-oracle#unichain-mainnet:~:text=%2D-,Unichain%20Mainnet,-Pool
=> Update oracle for Venus.ts

defi/src/protocols/data3.ts
Hey Llamas,
Kindly asking to update oracles for Cygnus Restake
Implementation Details: Cygnus Restake is using RedStone as the primary oracle for asset pricing. RedStone feeds are used as a cross-check for calculating user deposits value while minting cg-assets (cgUSD, clETH, Cygnus-stBTC…)
Wrong price provided by RedStone can lead to excess mint/ redemption of Cygnus assets and exploit of value within the protocol.
https://wiki.cygnus.finance/whitepaper/cygnus-network/how-does-cygnus-work
=> Update Oracles for Cygnus restake.ts

defi/src/protocols/data3.ts
Project Background Update
Our journey began with usdx.money, where we launched USDX, a delta-neutral stablecoin designed to optimize DeFi yields while maintaining stability.
Now, we are expanding our ecosystem with the introduction of usd0x.money, featuring USD0x, a T-Bill-backed stablecoin. We believe USD0x has a broader market appeal and will drive greater real-world adoption of blockchain-based financial products.
To reflect on this expansion, we have rebranded from usdx.money to Stables Labs — a next-generation stablecoin infrastructure that encompasses multiple products beyond USDX, including USD0x and future innovations.
Stables Labs represents our long-term vision to build a unified financial ecosystem, bridging TradFi, CeFi, and DeFi, and delivering practical, scalable, and …
=> update  stables-labs-usdx

defi/src/protocols/data4.ts
Hey Llamas,
thanks to our community we just noticed that beraborrow was not assigned to RedStone due to spelling mistake in the code.
https://x.com/Khees_/status/1901980098128986563
=> Update spelling beraborrow Oracle.ts

defi/src/protocols/data3.ts
Chronicle is the sole oracle powering Maker. Currently though, only the MakerDAO portion is credited. Opening this PR to add the Maker RWA part as well.
=> Update Maker RWA description

defi/src/protocols/data3.ts
Layerbank uses eOracle to secure their markets on Hemi chain, 
Layerbank's github has all the contract addresses listed https://github.com/layerbank/contracts
Their `PriceCalculator` contract with address [0x9c5973Fbbe1C5C4E75f435f47a046663Cc613B6c](https://explorer.hemi.xyz/address/0x9c5973Fbbe1C5C4E75f435f47a046663Cc613B6c) is used to set the price feed for each support collateral asset. 
Following transactions were used to set the feeds for various assets 
- [brBTC](https://explorer.hemi.xyz/address/0x93919784C523f39CACaa98Ee0a9d96c3F32b593e)
- [enzoBTC](https://explorer.hemi.xyz/tx/0x846e64f92f9166819f2f9972383a602f907269feb4ed6f2e8f7d9c12b40e3cfa)
- [iBTC](https://explorer.hemi.xyz/tx/0xdc639d32941054ae3cef85e6afc77b841d0f2d71443fa57a8a9dbf77b81b7f05)
- …
=> add eOracle for Layerbank on hemi

defi/src/protocols/data4.ts
Would be great if we could make these small changes:
- Changing name to `Centrifuge Protocol` since we don't use `Pool` as branding anymore
- Updating `listedAt` to Aug 1 2024 since that is when TVL started accruing on this
- Adding links to audits
=> Update Centrifuge Protocol data

defi/src/protocols/data3.ts
Chronicle powers several Morpho vaults on Base listed below. Below you will find the adapters used to read from Chronicle oracles along with the corresponding oracle. We use Chainlink Morpho adapters since they are compatible.
- [0x06aE266A252E2ee96A4c05cFDa8163ED94379a5a](https://basescan.org/address/0x06aE266A252E2ee96A4c05cFDa8163ED94379a5a#code) - wstETH/USD
- [0x308b4C07e4FD4677F8d710660027d6D03845Cb83](https://basescan.org/address/0x308b4C07e4FD4677F8d710660027d6D03845Cb83#code) - cbETH/USD
- [0x4Eb7916682F59E25F824d8CE2a8F2318319296F6](https://basescan.org/address/0x4Eb7916682F59E25F824d8CE2a8F2318319296F6#code) - ETH/USD
- [0x6999f231968b8ea5288633388dab00db80299d7e](https://basescan.org/address/0x6999f231968b8ea5288633388dab00db80299d7e) - cbBTC/USD
- …
=> Update Morpho description

defi/src/protocols/data2.ts
Hi Llamas!
Orderly recently upgraded and uses Pyth Lazer for their Perps
https://orderly.network/docs/changelog/evm#february-25th%2C-2025-major-update
=> Update of Orderly Perps Oracle

defi/src/protocols/data3.ts
Zerolend uses eOracle price feeds for all their asset markets on the Hemi market.
Zerolend is an Aave V3 fork, with all assets supported on the primary market can be found here https://app.zerolend.xyz/market/?marketName=proto_hemi_v3
Any misreport on any of feeds can cause loss of TVL.
You can find eOracle price feeds here https://docs.eo.app/docs/eprice/feed-addresses/hemi
**Verification:**
Zerolend lists their Hemi AaveOracle contract address to be https://berascan.com/address/0xA249579e05fC7E66B1dbC939AB9A81C1acB1933b, which can be found on the docs here https://docs.zerolend.xyz/security/deployed-addresses. 
This contract isn't verified on the Hemi block explorer  but has the standard AaveOracle interface. The price feed used for any asset can be queried using the following cast …
=> Add eOracle for Zerolend on Hemi

defi/src/protocols/data4.ts
Hey Llamas,
Kindly asking to update oracles for Silo on Sonic.
Implementation Details: Sonic is using RedStone on isolated pools:
S - stS, $261m secured
wstkscUSD - USDC, $18.5m secured
SolvBTC.BBN - SolvBTC, $10m secured
PT-stS - S, $10m secured
PT-aUSDC - scUSD, $9m secured
S - scUSD, $5.5m secured
PTwstkscETH - ETH, $4m secured
PTwstkscUSD - USDC, $2.5m secured
wstkscETH - ETH, $1.5m secured
That sums up to $322m secured across pools by RedStone feeds which is ~60% of Silo's Sonic TVL. 
Just as a comparsion on pools where Chainlink is securing any of the included assets it adds up to $176.5m ~33%.
Data can be checked in their app here: https://app.silo.finance/
=> Update oracles for Silo on Sonic.ts

defi/src/protocols/data3.ts
Solayer uses Switchboard oracles exclusively to price all sUSD redemptions.
Documentation around sUSD redemptions and how Switchboard is queried can be found in the Solayer docs here: https://docs.solayer.org/assets/susd/protocol-info/oracle&price_feeds#api-overview
=> Oracles: Add Solayer SUSD to Switchboard supported protocols 

defi/src/protocols/data3.ts
Hey! Another request for you to add Stork as an oracle. It was tough to tell primary from secondary, but because Stork supports the highest number of feeds, we decided we'd submit it as primary.
Thanks!
=> Add Stork as oracle for EVAA

defi/src/protocols/data3.ts
Echelon ensures price feed security by checking for derivation between Switchboard and Pyth prices for multisource security. 
Echelon documentation on the multisource pricing tactics can be found in their documentation below.
https://docs.echelon.market/echelon/core/oracles
=> Oracles: Add Echelon to Switchboard supported protocols

defi/src/protocols/data3.ts
Echelon ensures price feed security by checking for derivation between Switchboard and Pyth prices for multisource security. 
Thala documentation on the multisource pricing tactics can be found in their documentation below.
https://docs.thala.fi/overview/move-dollar-mod/oracles#switchboard
=> Add Thala to Switchboard supported protocols

defi/src/api2/routes/index.ts, defi/src/api2/utils/craftParentProtocolV2.ts, defi/src/api2/utils/craftProtocolV2.ts, defi/src/api2/utils/index.ts, defi/src/utils/craftParentProtocol.ts
Introduce a feature to restrict the size of protocol responses by counting the number of keys in the response object. If the key count exceeds a specified threshold, certain data fields will be nullified to reduce the response size.
=> Add option to limit protocol response size

defi/src/utils/normalizeChain.ts
Celo is now an Ethereum L2
https://x.com/Celo/status/1904776407215202508
=> Add parent in Celo

coins/src/adapters/tokenMapping.json
PEAS token is unrecognized on the Sonic network so we are requestion to add mapping for the token.
=> Add PEAS token to tokenMapping.json for Sonic network

coins/src/adapters/index.ts, coins/src/adapters/rwa/cyclex.ts
* Added cyclex token in rwa. Fetched token price from the chainlink oracle.
1. `cd coins && npm install`
2. ` ts-node src/test.ts cyclex`
**output** 
```
==== Testing cyclex ====
(node:54976) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
on September 8, 2024 and reach end-of-support on September 8, 2025.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check blog post at https://a.co/cUPnyil
(Use `node --trace-warnings ...` to show where the warning was created)
[
{
SK: 1744108637,
PK: 'asset#base:0x14e3206c7146acbc9274af8e2b0beb4bb6e1ef54',
price: 1789.00003,
adapter: 'cyclex-rwa',
confidence: 0.8
},
{
SK: 0,
PK: 'asset#base:0x14e3206c7146acbc9274af8e2b0beb4bb6e1ef54',
price: 1789.00003,
symbol: 'CFAT',
decimals: 18,
redirect: …
```
=> feat: add cyclex fund rwa write

coins/src/adapters/yield/sandglass/index.ts
Sorry, but I updated the symbol for `tETH` mint in eclipse. 😊
=> bugfix: update the eclipse symbol

defi/src/protocols/data4.ts
category was assigned wrong on initial merge.
we is liquid staking, no yield aggregator
=> fix: berapaw wrong category

coins/src/adapters/tokenMapping.json
This PR adds support for the Noble Dollar (USDN). As the collateral of the token is solely M by M^0, we choose to use their Coingecko ID until we're directly supported there. This will be paired with an adapter PR to update the TVL computation of the Noble blockchain.
=> feat: support Noble Dollar

defi/src/protocols/data3.ts
Suilend uses an aggregate of Switchboard and Pyth prices to determine aggregate pricing and risk factors for cross collateral lending
Suilend documentation on price support via oracles can be found at:
https://docs.suilend.fi/security/risks
Integration source code can be found at: https://tinyurl.com/2454fla4
=> Oracles: Add Suilend to Switchboard supported protocols

defi/src/protocols/data3.ts
Hi
Updated oracles of Jupiter Perpetual and Tradoor 
Jupiter 
- they recently updated their docs and changed how they use price oracles
- it is now using Edge, Pyth and Chainlink
- below statement is also notable and i believe follows the description of an "Aggregator"
>  If two out of three oracles fail, no price update will happen.
Docs link
https://support.jup.ag/hc/en-us/articles/19355326396700-Jupiter-Perpetuals-price-oracles
Tradoor
- recently integrated Pyth
Docs Link
https://docs.tradoor.io/tradoor-user-guide-v2/others/oracle-data
Minor update on Avantis X account
=> Oracle and X update

defi/src/protocols/data4.ts
Hey Lamas, 
Kindly asking you to update Oracles for Felix on Hyperliquid. 
Oracle Provider(s): RedStone. 
Implementation details. Felix is using RedStone as the primary Oracle on all main pools. 
Documenation/Proof: https://usefelix.gitbook.io/felix-docs/advanced/risk-management#redstone-oracles
=> Update Oracles for Felix.ts

defi/src/protocols/data4.ts
Add LiquidOps Spearbit audit, all audits will be available at: https://docs.liquidops.io/security/audits
=> feat: add LiquidOps audits

coins/src/adapters/rwa/dinari.ts, defi/src/utils/symbols/symbols.json
This also adds support for SRLN.D, which will go into Plume's flagship staking protocol Nest on mainnet launch.
=> add Plume Mainnet to Dinari deployment

defi/src/protocols/data.ts
Hello Llamas,
We request to add RedStone as the main oracle for Venus on the BNB Chain. RedStone is currently the main Oracle for the two largest markets in Venus Core pool: BTC (~$846m) and BNB (~$652m) which adds up to ~$1.5b secured out of $2.5b. (60% of the TVL)
Documenation/Proof: https://docs-v4.venus.io/risk/resilient-price-oracle#bnb-chain
=> Update Oracles for Venus Core Pool.ts

coins/src/adapters/markets/sundaeswapv3.ts
This adapter is untested and will require modification from a DefiLlama team member. The current version of the adapter includes the correct query to collect the top 50 pools on SundaeSwap V3 and filters this list to only include pools with ADA being the other asset. Adding this adapter will allow DefiLlama to start tracking many currently untracked Cardano tokens including WMTX and MIDAS.
=> Add SundaeSwap V3 Popular Pools

defi/src/protocols/data3.ts
Hello, 
requesting to add RedStone as an oracle provider for Eigenpie. Their feeds are used both for yield calculation and for calculating the amount of receipt tokens when depositing into the vault.  RedStone could expose deposit vaults to significant risks through inaccurate valuations and yield calculations, potentially leading to losses, a drain of the vault or inefficient capital allocation.
Materials: https://docs.eigenpiexyz.io/native-restaking#redstone-oracles
=> update the orcale of Eigenpie from chainlink to RedStone

defi/src/protocols/data3.ts
Hi again,
Submitting a PR for Stork as the primary oracle for Helix. Looks like for mark prices it's split between Stork and Pyth, but for unique use-cases and index perpetuals, Helix uses solely Stork.
Thanks!
=> Add Stork as oracle for Helix

coins/src/adapters/tokenMapping.json, defi/src/constants/chainsByOracle.ts
- **fix(tokenMappings): Nibiru integrated with LayerZero and Stargate, adding several common ERC20s**. This pull request includes WETH, stNIBI (Liquid Staked NIBI), USDT, USDC, and USDC.arb, which are all live on Nibiru mainnet. 
- Remove duplicate chain called "cataclysm_1" because there's no separate chain
and everything can be pulled from "nibiru" in the TVL adapter repo
- This defillama-server PR will make it possible to add in DeFi apps like Omniswap to have TVL adapters with ERC20 tokens on Nibiru.  
https://github.com/DefiLlama/DefiLlama-Adapters/pull/14259
=> fix(tokenMappings): Nibiru integrated with LayerZero and Stargate, adding several common ERC20s

defi/src/protocols/data3.ts
Set Edge Oracle as primary on Adrena Protocol on Solana, adjusted Pyth to fallback oracle. 
Reference: https://x.com/AdrenaProtocol/status/1925828470573076631
=> Set Edge as primary oracle for Adrena Protocol 

defi/src/protocols/data3.ts
Layerbank now uses eOracle price feeds for its Manta Deployment (https://app.layerbank.finance/bank?chain=manta-pacific&network=manta-pacific). 
Layerbanks PriceCalculator contract on Manta - https://pacific-explorer.manta.network/address/0x38f4384B457F81A4895c93a7503c255eFd0746d2
The feed settings was executed in May, linking some of the above txs below - 
ETH - https://pacific-explorer.manta.network/tx/0x95677374bb7e0ca0f141e0cca3de5129aecf54e72ab3e6b83e805181fbaaf417
USDC - https://pacific-explorer.manta.network/tx/0xf0a37ecf829f771d27f8eab5f7e33b60dcb1f425531dc4c2e7b1e04f6231de1d
STONE - https://pacific-explorer.manta.network/tx/0xdccd1da9c19cfe24b656cb171de0cfc251b141d334c9960fdebd7fbf546679f9
wstETH - https://pacific-explorer.manta.network/tx/0xf8563861b5552d693fbc6f76ee80048e515dea5 …
=> update Oracle for Layerbank on Manta

defi/ui-tool/package.json, defi/ui-tool/src/dimensions.ts, defi/ui-tool/src/server.ts
This PR improves the UI tool's server management and reliability:
Changes:
- Separate React app start from server start for better process management
- Fix working directory issues for proper file access
- Add proper error handling for robustness
- Implement cleanup handlers for SIGINT and SIGTERM signals
- Add detailed logging for startup/shutdown events
- Fix port configuration (WebSocket: 8080, React: 5001)
- Ensure clean process termination to prevent hanging processes
Testing:
- Confirmed tool works with `npm run ui-tool`
- Verified clean shutdown with Control+C
- Checked for hanging processes
- Confirmed both browser tab and terminal can be closed safely
=> fix(ui-tool): improve server and React app management

defi/src/getOracles.ts
Currently, when calculating the TVS for an oracle, if a single protocol uses that oracle on multiple chains, the TVS from each chain overwrites the previous one instead of being added together.
=> fix: Correctly sum oracle TVS across multiple chains

defi/src/protocols/data3.ts
Hello DefiLlama team,
Requesting to add Peapods Finance to DIA Oracles TVS.
Oracles: DIA
Implementation Details: Enabling external lending and borrowing protocol integrations for the Peapods Finance native PEAS token (on all markets). Includes additional price feeds for SERV, NPC, XMW.
Documentation: Peapods request on forum (https://forum.diadata.org/t/cdr-091-peapods-finance-asset-price/1011/5), partnership details (https://www.diadata.org/blog/post/partnership-with-peapods-finance/)
Failure Scenario: Stale price data can lead to vaults being liquidated (as these are leveraged, more susceptible to price variation), which can result in the TVL of each vault being under risk.
=> Add DIA Oracles to Peapods Finance

defi/src/protocols/data4.ts
Hello DefiLlama Team! 
Requesting to add RedStone as an oracle provider for HyperBeat. HyperBeat uses RedStone Oracles as a security check before accepting deposits into Hyperliquid vaults to ensure proper receipt tokens for all assets (i.e. hbHYPE, hypeETH, hypeBTC) allocation calculations. This additional validation layer ensures that deposit vaults are safe, compliant with risk parameters, and operating under accurate market conditions.
Incorrect oracle data from RedStone could expose deposit vaults to significant risks through inaccurate valuations and yield calculations, potentially leading to losses, a drain of the vault or inefficient capital allocation. Since RedStone provides critical data for vault calculations its reliability directly impacts the vault system's stability.
=> add: redstone oracle

defi/src/storeEmissionsUtils.ts
=> emissions allow breakdown even if last 30d no emissions

coins/src/adapters/tokenMapping.json
- Add WBTC and WETH tokens on Coti
- Verified decimals on 
WBTC: https://mainnet.cotiscan.io/address/0x8C39B1fD0e6260fdf20652Fc436d25026832bfEA?tab=read_proxy
WETH: https://mainnet.cotiscan.io/address/0x639acc80569c5fc83c6fbf2319a6cc38bbfe26d1?tab=read_proxy
=> Add WETH and WBTC to Coti chain mapping

defi/src/protocols/data4.ts
Hey @realdealshaman we have rebranded CVEX to Jetstream, you can check cvex.xyz is now redirecting to jetstream.trade.
Now we would appreciate if we can change the branding on defillama as well. Please see all changes required in the PR, new logo is attached below.
Thank You!
=> CVEX Rebranding

defi/src/protocols/data4.ts
Hi, Llamas. I was told in a ticket that the TVS for Morpho has been moved with the curator and to open a PR here.
Chronicle powers several Morpho vaults on Base and Unichain listed below. Below you will find the adapters used to read from Chronicle oracles along with the corresponding oracle. We use Chainlink Morpho adapters since they are compatible.
BASE:
[0x06aE266A252E2ee96A4c05cFDa8163ED94379a5a](https://basescan.org/address/0x06aE266A252E2ee96A4c05cFDa8163ED94379a5a#code) - wstETH/USD
[0x308b4C07e4FD4677F8d710660027d6D03845Cb83](https://basescan.org/address/0x308b4C07e4FD4677F8d710660027d6D03845Cb83#code) - cbETH/USD
[0x4Eb7916682F59E25F824d8CE2a8F2318319296F6](https://basescan.org/address/0x4Eb7916682F59E25F824d8CE2a8F2318319296F6#code) - ETH/USD …
=> Update Steakhouse description

defi/src/protocols/data4.ts
Copy from previous post (https://github.com/DefiLlama/defillama-server/pull/10115)
Hello DefiLlama team,
Requesting to add International Meme Fund to DIA Oracles TVS.
Oracles: DIA
Implementation Details: IMF is using DIA to support price feeds for their underlying assets for borrowing from the USDS market (MOG, PEPE, JOE) - and additional assets as requested (SPX & IMF).
Documentation: DIA request on forum (https://forum.diadata.org/t/cdr-094-international-meme-fund-token-price-feed/1028), & partnership details (https://www.diadata.org/blog/post/dia-oracles-imf-lending-defi/)
Failure Scenario: The collateralization ratio is used for determining the borrowed asset, if the underlying assets (MOG, PEPE, JOE) are incorrectly priced, it can result in the incorrect amount of USDS minted and …
=> Add IMFv2 to DIA Oracles

defi/src/protocols/data4.ts
Hello DefiLlama team,
Requesting to add Hydration Lending to DIA Oracles TVS.
Oracles: DIA
Implementation Details: DIA will deploy, monitor, and maintain 10 market-based price oracles for HydraDX’s on-chain money market. The assets which will be initially supported are: WBTC, WETH, DOT, VDOT, and additional assets will be added upon request to support new markets.
Documentation: Approval of governance proposal on the Hydration DAO forum (https://hydration.subsquare.io/treasury/proposals/23)
Failure Scenario: Underlying asset prices will determine the borrow ratio, if the price of the underlying assets are not correctly determined then can result in overborrowing, therefore allowing undercollateralization and liquidations to occur.
Thank you,
Josh
=> Add Hydration Lending to DIA Oracles

defi/src/adaptors/data/fees/config.ts
As jumper charges 0 fees and all the fee goes to bridges, so no point in showing double fees
=> Delist Jumper-exchange Fees adapter

defi/src/protocols/data4.ts
Hey @realdealshaman ! Bit of a more complicated one here. 63.6% of TVL secured by Stork Contracts through the StorkChainlinkAdapter for nBASIS, nALPHA, and nCREDIT on RE7's Vault on Plume.
=> Add Stork as oracle for RE7 on Plume

defi/src/protocols/data4.ts
Oracle Provider(s): Edge
Implementation Details: Steakhouse use Edge Oracles for their vaults on the Morpho instance on Corn network
Documentation/Proof: Can see use of Chaos oracles here: https://cornscan.io/address/0xFe423163bfEe287a132E656D5EC4a363B8A2B4f3/contract/21000000/readContract#F1
=> Add Chaos Edge to Steakhouse finance on Corn

defi/src/api2/cron-task/genFormattedChains.ts, defi/src/api2/cron-task/index.ts, defi/src/api2/routes/index.ts
Most of the logic is same as this file: https://github.com/DefiLlama/defillama-server/blob/master/defi/src/getFormattedChains.ts
changes are:
- instead of relying on api.llama.fi data, we use the files generated in previous cron step
- instead of loading chain list and chain tvl data (& prices) each time, we fetch them once and use it to generate all chains2/category data
=> Pre-generate chains2 data instead of computing it each time

defi/src/protocols/data4.ts
Changed PBG category from Reserve Currency to Onchain Capital Allocator
Reason: although the project's native token is a Reserve Currency, "Onchain Capital Allocator" better describes the actual underlying smart contract. Most competing projects on other chains also seem to categorize themselves as "Onchain Capital Allocator".
=> Changed PBG category

defi/src/protocols/data4.ts
Hey Llamas,
Kindly asking to add RedStone as the second primary oracle for HyperLend on Hyperliquid. RedStone is integrated on kHYPE (25%), UBTC (6,7%), UETH (3,6%), sUSDe (0.1%), USR markets which account for ~35,4% of HyperLend's TVL. 
Since those markets are in Core (pooled) pools (aave fork) and we secure significant % of tvl in case of manipulation on those markets whole Hyperlend TVL would be at risk.
Documenation/Proof:
Oracle used can be checked in the "Oracle provider" section in the market details -> https://app.hyperlend.finance/markets/0xfD739d4e423301CE9385c1fb8850539D657C296D
=> Update Oracles for Hyperlend.ts

defi/src/protocols/data4.ts
Hey Lamas,
Kindly asking you to update Oracles for SoSoValue
Oracle Provider(s): RedStone.
Implementation details: SoSoValue is using RedStone the primary Oracle on all main pools.
Documenation/Proof: https://sosovalue.gitbook.io/sosovalue-indices/solution-design/overview
=> Update Oracles for SoSoValue.ts

defi/src/protocols/data4.ts
We're requesting a name changing as the protocol is legacy at this point.
thank you for your time!
=> Name change on canary protocol metadata

defi/src/protocols/data4.ts
gm!
Ouroboros Capital (Risk Curator) managed a vault on Morpho Eth mainnet, which is their entire reported TVL (https://app.morpho.org/ethereum/vault/0x2F21c6499fa53a680120e654a27640Fc8Aa40BeD/openeden-usdc-vault). 
The vault allocates 98%+ capital to the PT-cUSDO-20NOV2025 / USDC market. (https://app.morpho.org/ethereum/market/0x8a71a66ac828c2b6d4f8accce5859aba0822b502f3833bec4aff09479affffdb/pt-cusdo-20nov2025-usdc), which is secured by eOracle data feed. 
Verification - 
- Go to advanced tab within the market page, go to the morpho oracle address on the bottom of the page - https://etherscan.io/address/0x0dF910a47452B995F545D66eb135f38D0FbB142E#readContract
- call BASE_FEED_1 on the morpho oracle, it returns - https://etherscan.io/address/0xCE84fD399620B7D20e18AB6009Fc8A0cdaad880f#code, …
=> add eOracle to ouroboros capital oracles

defi/src/protocols/data4.ts
Re7 Labs Cluster's cbBTC market (TAC)(https://app.euler.finance/vault/0x2eF66758705426e7BF598669AEf23eE9b9CC3088?network=tac) is secured by eOracle. 
Steps to verify - 
1/ visit the oracle router here https://explorer.tac.build/address/0x51e0CAcc951ed4402366572eaCd120C8B28853d4?tab=read_write_contract
2/ call getConfiguredOracle with base as cbBTC (0x7048c9e4aBD0cf0219E95a17A8C6908dfC4f0Ee4) and quote as USD(0x0000000000000000000000000000000000000348), it returns the Euler Chainlinkadapter here https://explorer.tac.build/address/0x5777baB47b2705C8576aBc4995589157E59384a1?tab=contract
3/ call feed() on the adapter, it returns https://explorer.tac.build/address/0xaE5Dc951d55535679252Cff49E89Af8cEcbf5E1f which is deployed and maintained by eOracle. 
You can find eOracle TAC feeds here …
=> add eOracle as primary for Re7 on TAC

defi/src/protocols/data3.ts
Hi DefiLlama team! Echelon is now being secured by Chainlink oracles! You can find the official announcement [here](https://x.com/EchelonMarket/status/1960734061938532857) and the proof [here](https://docs.echelon.market/echelon/core/oracles).
=> Updated Echelon oracles

defi/src/protocols/data2.ts
Hey Llamas,
Kindly asking to update oracles for Sentiment on Hyperliquid L1
Implementation Details: Sentiment is using RedStone as the primary oracle on main pools: wHYPE, wstHYPE, USDT, USDe
https://docs.sentiment.xyz/contracts/v2/Deployments#oracles
=> Update oracle for Sentiment on Hyperliquid.ts

defi/src/protocols/data4.ts
Hello DefiLlama team,
Requesting to add Unilend to DIA Oracles TVS.
Oracles: DIA
Implementation Details: DIA is supporting the Unilend markets for all their price feeds on Units Network.
Documentation: https://x.com/Unilendone/status/1964976269772071391
Failure Scenario: Underlying asset prices will determine the borrow ratio, if the price of the underlying assets are not correctly determined then can result in overborrowing, therefore allowing undercollateralization and liquidations to occur.
Additionally, please add Units Network to the list of supported networks under DIA's oracle. Happy to create another PR request for this if necessary.
Thank you,
Josh
=> Add Unilend to DIA Oracles

coins/src/adapters/tokenMapping.json
fix osBGT mapping typo
Add mappings for missing API price tokens:
- add wrapped SOL (wormhole bridged)
- add yBGT (official coingecko listing, wasn't recognizing a price)
- add solvBTC.BNB (official coingecko listing, wasn't recognizing a price)
=> Berachain token mappings update

defi/src/protocols/data4.ts
Update the primary oracle for Takara Lend.  Team has switch a majority of the primary oracles to Api3
Proof in markets          
https://app.takaralend.com/market/WSEI
https://app.takaralend.com/market/spSEI
https://app.takaralend.com/market/iSEI
https://app.takaralend.com/market/uBTC
https://app.takaralend.com/market/MBTC
https://app.takaralend.com/market/SBTC
=> Update Takara Lend primary oracle
