defi/src/protocols/data2.ts
add chain prefix to address (ZK era)
=> add chain prefix to address (ZK era)

defi/src/protocols/data2.ts
=> change category sharpe

defi/src/protocols/data2.ts
remove polygon zkevm from 0vix test
=> remove polygon zkevm from 0vix test

defi/src/protocols/data2.ts
add Polygon zkevm chain to 0vix
=> add Polygon zkevm chain to 0vix

defi/src/protocols/data.ts
=> remove TangoSwap test

defi/src/utils/normalizeChain.ts
=> fix server (smartbch)

defi/src/utils/normalizeChain.ts
=> Smart BCH (1)

defi/src/protocols/data2.ts
=> Final fix server

defi/src/protocols/data2.ts
=> Witnet Oracle

defi/src/protocols/data2.ts
=> Delist SyncDex

defi/src/protocols/data2.ts
=> add treasury lsdx finance

defi/src/protocols/data2.ts
=> Re-List SyncDex

coins/src/adapters/tokenMapping.json
=> add bnb and reflect

coins/src/adapters/other/distressedAssets.ts
=> add DUEL distressedAssets

coins/src/adapters/other/distressedAssets.ts
=> add CoUSD to distressAssets

defi/src/protocols/parentProtocols.ts
=> update icon camelot

defi/src/protocols/data2.ts
add parentProtocol field for aevo
=> add parentProtocol field for aevo

coins/src/adapters/tokenMapping.json
=> add tokens umee

defi/src/protocols/data2.ts
update description dove swap v3
=> update description dove swap v3

defi/src/protocols/data2.ts
=> Update address Genius Yield

defi/src/protocols/data.ts, defi/src/protocols/data2.ts, defi/src/protocols/parentProtocols.ts
=> Add compound IDs (governance)

defi/src/protocols/data2.ts
unlist tegro finance (while we fix)
=> unlist tegro finance (while we fix)

defi/src/protocols/data2.ts
=> relist syncdex finance

defi/src/protocols/data2.ts
=> keep unlisted syncdex

defi/src/protocols/data2.ts
=> add correct address abc pool

defi/src/protocols/data2.ts
=> remove toucan (regen)

defi/src/protocols/data.ts
=> add oracle buffer finance

defi/src/protocols/data2.ts
=> keep governance token tbtc

defi/serverless.yml
Reverts DefiLlama/defillama-server#2996
=> Revert "Disable new envs"

defi/src/protocols/data2.ts
=> add oracle apollox

defi/src/protocols/data.ts, defi/src/protocols/data2.ts, defi/src/protocols/parentProtocols.ts
=> replace twitter dao maker

defi/src/protocols/data2.ts
=> fix module

defi/src/protocols/data2.ts
=> update category apex protocol

defi/src/protocols/data2.ts, defi/src/protocols/parentProtocols.ts
=> update name izumi

defi/src/protocols/parentProtocols.ts
=> add correct link to enosys

defi/src/protocols/data2.ts
=> add dove token server

defi/src/protocols/data2.ts
=> correct module

defi/src/protocols/data2.ts
gm llama sirs
requesting your review to add Polynomial oracle under Pyth
https://twitter.com/PolynomialFi/status/1640347721725771780?s=20
=> add Polynomial oracle

defi/src/protocols/data.ts
=> illuvium treasury

defi/src/protocols/data.ts
=> add treasuries

defi/src/protocols/data2.ts
=> fix display name smbswap v2

coins/src/adapters/tokenMapping.json
@Define101 - just picking up from @MikeR808's PR #3052, and adding STOSMO
=> Kujira STATOM & STOSMO

coins/src/adapters/moneyMarkets/compound/index.ts
spelled with O instead of 0 to make code work :)
docs: https://docs.0vix.com/developers/contract-addresses/mainnet
=> added 0VIX (pos & zkevm)

defi/src/protocols/data.ts
=> change token address torchain

defi/src/protocols/data.ts, defi/src/protocols/data2.ts
=> add more treasuries

defi/src/protocols/data2.ts, defi/src/protocols/parentProtocols.ts
Should be merged in combination with https://github.com/DefiLlama/DefiLlama-Adapters/pull/6139
=> Add Blur Lend

defi/src/protocols/data2.ts
=> really fix

defi/src/protocols/data.ts
=> add treasury iq

defi/src/protocols/data2.ts
=> add treasury neutra

defi/src/protocols/data2.ts
Migrate LBR token
New Address : 0xF1182229B71E79E504b1d2bF076C15a277311e05
=> Migrate LBR token

defi/src/protocols/data.ts
add treasury umami + check server
=> add treasury umami + check server

defi/src/protocols/data2.ts
add binance oracle to helio protocol
=> add binance oracle to helio protocol

defi/src/protocols/data2.ts
=> new description vaultka

defi/src/protocols/data2.ts
=> add treasury flokifi

defi/src/protocols/data2.ts
=> add treasury

defi/src/adaptors/data/dexs/config.ts, defi/src/protocols/data2.ts
SatoshiSwap has been rebranded to SatoshiCoreSwap
Rebrand Announcement
https://medium.com/@satoshicoreswap/project-is-now-upgraded-to-satoshicoreswap-airdrop-for-new-account-followers-32bec4d6891e
=> Change SatoshiSwap to SatoshiCoreSwap

defi/src/protocols/data2.ts
Change description to reflect Archly's multiple chain deployments
=> Update description/chains for multichain status

defi/src/protocols/data2.ts
=> Fix server error

defi/src/protocols/data.ts, defi/src/protocols/parentProtocols.ts
add treasury to parentProtocol
=> add treasury to parentProtocol

defi/src/protocols/data.ts, defi/src/protocols/data2.ts
decubate description  + audit smardex
=> decubate description  + audit smardex

defi/src/protocols/data2.ts
antfarm finance category change
=> antfarm finance category change

coins/src/adapters/tokenMapping.json
Add mapping for tokens bridged via TON Bridge:
- USDT
- USDC
- WBTC
- DAI
=> add mapping for official TON bridge

defi/src/protocols/data2.ts
=> add audit link to tsunami

defi/src/protocols/data.ts
=> add audit links tron

defi/src/protocols/data2.ts
Modify lybra finance protocol audit_links.
=> Modify lybra finance protocol audit_links

defi/src/protocols/parentProtocols.ts
=> fix origin

defi/src/protocols/data2.ts
remove fork information from avely
=> remove fork information from avely

defi/src/protocols/data2.ts
=> fi9x server

defi/src/protocols/data2.ts
gm llama sirs
requesting your review to add protocols that are using Pyth 
- Interest Protocol
https://twitter.com/interest_dinero/status/1656688554997874688?s=20
- Beluga Protocol
https://twitter.com/Belugadex/status/1656298049273204736?s=20
- Forge SX
https://twitter.com/forge_sx/status/1652355248424353794?s=20
Thank you very much
=> add protocols oracle

defi/src/protocols/data2.ts
=> add cgid to wefi

defi/src/protocols/data2.ts
=> add treasury equilibre

defi/src/nfts/parentCompanies.ts
=> add RTFKT collection

coins/src/adapters/other/gmd.ts
Adds gmdUSDT, gmdETH and gmdBTC
Needed to correct TVL calculations for protocols where these assets are supplied
=> Add missing gmd assets

defi/src/nfts/parentCompanies.ts
add art block, azuki and doodles
=> add art block, azuki and doodles

defi/src/nfts/parentCompanies.ts
=> add more parentCompanies

defi/src/protocols/data2.ts
update information Holdstation
=> update information Holdstation

defi/src/protocols/data.ts, defi/src/protocols/data2.ts
gm llama sers
requesting your review to add protocols that are using Pyth
- Lyra Finance
https://twitter.com/PythNetwork/status/1661573348609105920?s=20
- Vela Exchange
https://twitter.com/vela_exchange/status/1662131973702426625?s=20
thank you
=> add protocol oracle

defi/src/protocols/data2.ts
=> update category glif

defi/src/protocols/data2.ts
=> new twitter acc dexilla

defi/src/nfts/parentCompanies.ts
=> add more parents

defi/src/protocols/data.ts
gm llama sers
requesting your review to add Pyth as one of the oracles securing Venus 
https://twitter.com/bradherenow/status/1665668129916178433?t=bnAUk4GOpTlM2Ql28SQwPg&s=19
https://app.venus.io/governance/proposal/123
=> Add Venus oracle 

defi/src/nfts/parentCompanies.ts
remove single projects + add more
=> remove single projects + add more

defi/src/protocols/data3.ts
=> add unibot team

defi/src/protocols/data2.ts, defi/src/protocols/data3.ts, defi/src/protocols/parentProtocols.ts
=> change sudoswap letter

defi/src/protocols/data.ts
change sperax usd address to govenance
=> change sperax usd address to govenance

defi/src/protocols/data3.ts
=> feat: add audit report

defi/src/protocols/data.ts
=> change category pNetwork

defi/src/protocols/data2.ts
=> jones dao change category

defi/src/protocols/data2.ts
Add new token address for neutra finance
=> Add new token address for neutra finance

defi/src/nfts/parentCompanies.ts, defi/src/protocols/data3.ts
parent quirklings + new contract
=> parent quirklings + new contract

defi/src/protocols/data3.ts
=> fix logo litx

defi/src/protocols/data3.ts
=> remove token info blazestake

defi/src/protocols/data3.ts
add stablecoin info for gravita
=> add stablecoin info for gravita

defi/src/protocols/data2.ts
deslit kleva lend + alpaca lending
=> deslit kleva lend + alpaca lending

defi/src/protocols/data2.ts, defi/src/protocols/data3.ts
gm llama sirs
requesting your review to add these protocols under Pyth
- Cetus https://twitter.com/CetusProtocol/status/1674124654192267265?s=20 
- HMX https://twitter.com/HMXorg/status/1673700210365587456?s=20 -
- Mars https://twitter.com/mars_protocol/status/1671137706770853889?s=20 -
- Tsunami Finance https://twitter.com/PythNetwork/status/1583172352627859456?s=20 - t
=> add Pyth to protocols

defi/src/protocols/data.ts
gm llama sirs
requesting your review to add a Pyth user in Pika protocol under Pyth
https://twitter.com/PikaProtocol/status/1676602233507414016?t=4WrtW8Nez97sf129KSDWFg&s=19
thank you
=> add pyth as oracle

coins/src/adapters/tokenMapping_added.json
coins: add ibc coins of crescent dex
=> coins: add ibc coins of crescent dex

defi/src/protocols/data3.ts
gm llama sers
requesting your review to add Pyth as an oracle for Bucket Protocol
https://twitter.com/bucket_protocol/status/1676050031525371905?s=20
thank you
=> add pyth to bucket

defi/src/protocols/data3.ts
=> add github to lybra finance

defi/src/protocols/data3.ts
gm llama sirs
requesting your review to add Pyth to Pinnako as the oracle 
https://twitter.com/PinnakoDex/status/1664088824333619201?s=20
thank you
=> add pinnako oracle

defi/src/protocols/data2.ts
Adds new audit link to Sommelier project
=> sommelier: update audit link

defi/src/protocols/data.ts
Updated `description`, `chains`, and `audit-links` for Rubicon
=> Update Rubicon data

defi/src/protocols/data3.ts
remove oracle information from Raft
=> remove oracle information from Raft

coins/src/adapters/tokenMapping_added.json
=> remove extra ,

defi/src/protocols/data2.ts
=> add token to pirex

defi/src/protocols/data3.ts
gm llama sirs
requesting your review to add Aevo as a Pyth oracle user
https://twitter.com/aevoxyz/status/1680927361020342273?s=20
=> add aevo oracle

defi/src/protocols/data2.ts
Hi, we need to update description for Streamflow on Defillama.
Thank you!
=> Streamflow: update description

defi/src/protocols/parentProtocols.ts
=> add treasury to kyberswap

defi/src/protocols/data2.ts
Davos Protocol address and symbol
=> Davos Protocol address and symbol

defi/src/protocols/data2.ts
Update project description for Sommelier
=> sommelier: update project description

coins/serverless.yml
Reverts DefiLlama/defillama-server#3860
=> Revert "delete coins chains endpoint"

defi/src/protocols/data2.ts
=> add info jojo

defi/src/protocols/data3.ts
gm llama sirs,
requesting your review to add Pyth as the oracle for Lendle on Mantle
https://twitter.com/PythNetwork/status/1684118909530804224
=> lendle oracle support

coins/src/adapters/other/distressedAssets.ts, coins/src/fetchCoingeckoData.ts
Reverts DefiLlama/defillama-server#3928
=> Revert "Distr"

defi/src/adaptors/handlers/getOverviewProcess/index.ts, defi/src/adaptors/handlers/helpers/generateProtocolAdaptorSummary.ts
Reverts DefiLlama/defillama-server#3940
=> Revert "Add extra 30d"

coins/src/adapters/index.ts, coins/src/adapters/markets/balancer/balancer.ts, coins/src/adapters/markets/balancer/index.ts, coins/src/adapters/yield/misc4626/tokens.json, coins/src/fetchCoingeckoData.ts
Reverts DefiLlama/defillama-server#3947
=> Revert "Distressed assets patching"

defi/src/protocols/data3.ts
Update
- audits
- forkedFrom
- oracles
- audit_links
=> Update Gambit Data

defi/src/protocols/data3.ts
gm llama sirs,
requesting your review to add Pyth oracle to these protocols
- Reax Assets
- Reax Lending
=> add reax oracle

defi/src/protocols/data3.ts
gm llama sirs,
would like to request for help in adding Pyth to Sable Finance as its oracle
https://twitter.com/SableFinance/status/1646501815918411776?s=20
=> add sable oracle

defi/src/protocols/data3.ts
gm llama sirs,
requesting your review to add Pyth as the oracle for EDE Base
https://twitter.com/ede_finance/status/1689897137667252224
thank you
=> add ede base oracle

defi/src/protocols/data2.ts
=> Add audit report - Update data2.ts

defi/src/protocols/data2.ts, defi/src/protocols/data3.ts
gm llama sirs, 
requesting your review to add Pyth as the oracle for both Covo V1 and V2
https://covo-finance.gitbook.io/covo/trading/orders/order-settlement
https://covo-finance.gitbook.io/covo/trading/orders/order-settlement
thank you
=> add covo finance oracle

defi/src/protocols/data3.ts
=> add magnate-finance info

coins/src/adapters/index.ts, coins/src/adapters/yield/beefy/beefy.ts, coins/src/adapters/yield/quickperps/index.ts, coins/src/adapters/yield/quickperps/quickperps.ts
Haven't tested this yet due to issues running `npm i` in defi/
=> add Quickperps and Yama QLP on Polygon zkEVM

coins/src/adapters/yield/chai.ts
https://chai.money is a Dai Savings Rate wrapper.
=> Add Chai adapter

defi/src/adaptors/data/derivatives/config.ts, defi/src/adaptors/data/dexs/config.ts, defi/src/adaptors/data/fees/config.ts
Reverts DefiLlama/defillama-server#4292
=> Revert "enable ktx-finance"

defi/src/protocols/data3.ts
We would like update protocol url to marketing site, for better management of future protocol launch. Thank you!
=> Update metadata of Hodlify

coins/src/adapters/tokenMapping.json
=> add tokens to kroma chain

coins/package.json
Reverts DefiLlama/defillama-server#4428
=> Revert "cg2 script"

defi/src/protocols/data3.ts
=> Update Circuit Protocol

defi/src/governance/icp.test.ts, defi/src/governance/icp.ts, defi/src/governance/types.ts
This MR proposes the following changes:
1. Formatting of the NNS integration
2. Change proposal title from proposal.topic to proposal.title
3. Remove outdated constants by fetching data directly from the canister
4. Remove hardcoded metadata by metadata function call
5. Add link property to the proposal object
=> ICP-NNS governance updates

defi/src/storeTvlInterval/computeTVL.ts
Reverts DefiLlama/defillama-server#4655
=> Revert "coins2"

defi/src/protocols/data.ts
gm llama sirs
requesting your review to add 2 new protocols that use Pyth
Angle
https://x.com/PythNetwork/status/1713963107025076433?s=20
Thales
https://x.com/PythNetwork/status/1694002716325126649?s=20
thank you
=> add pyth protocols

defi/src/protocols/data3.ts
gm llama sers
requesting your review to add Lyve oracles 
thank you
=> add lyve oracle

coins/src/adapters/tokenMapping.json
Following tokens have been added against elysium chain:
PYR
WMATIC
WETH
USDT
Metaverse (Genso)
Please merge PR
=> Update tokenMapping.json added 5 tokens for elysium chain

coins/src/adapters/tokenMapping_added.json
remove duplicated entries from tokenmapping_added
=> remove duplicated entries from tokenmapping_added

coins/src/adapters/tokenMapping_added.json
=> add usdy tokenmap

coins/src/adapters/rwa/ondo.ts
=> Ondo: Update Contract call for USDY && USDYc

defi/src/protocols/data3.ts
Changed url from beta.ennead.farm to app.ennead.farm and fixed symbol (neadRam)
=> Update ennead data

defi/src/protocols/data2.ts, defi/src/protocols/data3.ts
gm llama sirs
requesting your review to add these 2 protocols under Pyth oracle
CoffeeDex 
https://x.com/coffee_vedex/status/1716823967087141119?s=20
Mu.exchange
https://docs.mu.exchange/available-pairs
thank you
=> add pyth powered protocols

defi/src/protocols/data2.ts
Requesting to add Chainlink and RedStone Oracles to Sommelier
Materials:
https://sommelier-finance.gitbook.io/sommelier-documentation/smart-contracts/oracle-usage-and-asset-pricing
https://twitter.com/sommfinance/status/1692567027787923532
=> Sommelier: Update Oracles

coins/src/adapters/markets/stargate/contracts.json, coins/src/adapters/markets/stargate/index.ts, coins/src/adapters/utils/gasTokens.ts
This PR is untested as I do not know how to. I'm missing `aws-sdk` apparently. Assumed it was something that I may not be able to test locally.
=> feat(stargate): Add support for Kava

defi/src/protocols/data.ts
- Update oraclesByChain
- Checksum token address
- Update audit link to refer dopex docs as that is updated to reflect all the newest audits
=> Update data.ts for dopex

defi/src/protocols/data2.ts
gm llama sirs
requesting your review to add the oracles for Bluefin
https://learn.bluefin.io/docs/bluefin-101/oracle-and-index-price
=> add bluefin oracle

coins/src/adapters/tokenMapping.json
Reverts DefiLlama/defillama-server#5079
=> Revert "Add wan-bridge cross-token price mapping."

defi/src/protocols/data3.ts
hey! Announcement here and retweeted by the project.
https://x.com/API3ECO/status/1732445010514297088?s=20
=> Update oracle for Myso v2 on Mantle

coins/src/adapters/yield/mean-finance/index.ts
We are now adding xDAI / Gnosis chain to Mean Finance, and we are re-enabling BNB also
=> feat: add xdai to mean finance

defi/src/protocols/data3.ts
gm sirs
requesting your review to add a few protocols that have used Pyth
- Quickperps
https://perps-docs.quickswap.exchange/
- Cryptex V2
https://docs.cryptex.finance/pi/intro
Cryptex Pi is an improved version
thank you
=> add pyth end users

defi/src/protocols/data2.ts, defi/src/protocols/data3.ts
gm llama sirs
requesting your review to Pyth to protocols as their oracle
- Horizon 
https://horizonprotocol.medium.com/horizon-futures-dual-oracles-and-fees-15f401478066
- LogX
https://logx-1.gitbook.io/logx-docs/logx-perp-dex/trading-overview#price-oracle
- Metavault Derivatives V2
https://x.com/metavaulttrade/status/1734226609400631602?s=46&t=OKvmuZPFLfHJvsQxDSh6LA
https://lineascan.build/address/0x359a473f73ff13cd651b92a877ec0dcfde1a6cf7
Thank you
=> add pyth users

defi/src/protocols/data3.ts
Hey ! 
I have just updated Antfarm finance project description, since it fits more with the vision we want to share about our project.
=> update Antfarm finance description

defi/.gitignore, defi/src/cli/buildRequires.ts, defi/src/cli/buildTvlModuleData.js, defi/src/cli/checkChart.ts, defi/src/cli/customFillAll.ts, defi/src/cli/fillLast.ts, defi/src/cli/fillOld.ts, defi/src/cli/fillOldChain.ts, defi/src/cli/old-scripts/cacheTest.ts, defi/src/cli/old-scripts/customFillOhm.ts, defi/src/cli/old-scripts/huobi_stUSDT.ts, defi/src/cli/protocolStats.ts, defi/src/cli/recomputeDaily.ts, defi/src/cli/temp/stUSDT2_hourly.ts, defi/src/cli/utils/importAdapter.ts, defi/src/protocols/data.test.ts, defi/src/protocols/import.test.ts, defi/src/runLocalTVL.ts, defi/src/storeTreasuryInterval.ts, defi/src/storeTvlInterval/storeTvls.ts, defi/src/storeTvlTask.ts, defi/src/utils/imports/importAdapter.ts
Reverts DefiLlama/defillama-server#5224
=> Revert "Revert "use mock tvl adapter functions to reduce build time""

defi/src/protocols/data2.ts
As per discussion [here](https://github.com/DefiLlama/defillama-server/pull/4902) and also [here](https://discord.com/channels/823822164956151810/823822533974425621/1184658267058745415).
=> remove redstone from sommelier

defi/src/protocols/data3.ts
We lost access to our Twitter account and had to create a new one.
=> update tai.money twitter account

defi/src/protocols/data3.ts
Submit  Zomma Protocol audit reports
=> Add Zomma security audit link

coins/src/adapters/liquidStaking/pxeth/abi.json, coins/src/adapters/liquidStaking/pxeth/index.ts, coins/src/adapters/liquidStaking/pxeth/pxeth.ts
Create a price adapter based on the total ETH on the protocol.
=> Add price adapter for pxETH

coins/src/adapters/tokenMapping_added.json
=> add rusdt to roostock chain

defi/src/protocols/data3.ts
Update Weft Finance CoinGecko ID
=> Update Weft Finance CoinGecko ID

defi/src/protocols/data3.ts
Add #PoweredByPyth hashtag to TASHI protocol description
=> change TASHI description

defi/src/protocols/data3.ts
=> modifications commit #5509

defi/src/protocols/data3.ts
Correcting the website link from https://stage.kelpdao.xyz to https://kelpdao.xyz
=> Update KelpDAO website link

coins/src/adapters/markets/steer/steer.ts
=> Bump chains and endpoints

defi/src/protocols/data2.ts
Added the link to show the audit of bluefin
=> adding docsend link for audit trail for Bluefin

coins/src/adapters/tokenMapping_added.json
Adding the Fuzion Token to the Kujira Network
=> Add Fuzion Token

coins/src/adapters/markets/steer/steer.ts
Hi team
simply reducing the chains for tracking tokens as the subgraph links keep breaking + we only are using polygon and arbitrum
thanks for your time
=> Limit to poly and arb

defi/src/protocols/data3.ts
=> Update aspida info

defi/src/protocols/data.ts
=> add oracle field to mento

coins/src/adapters/tokenMapping_added.json
add tokenMapping for Zeta tokens
=> add tokenMapping for Zeta tokens

defi/src/protocols/data3.ts
gm llama sers
requesting your review to add ionic as a pyth user
https://x.com/modenetwork/status/1754878770840752421?s=20
https://x.com/PythNetwork/status/1753435755521642518?s=20
thank you
=> add pyth to ionic

defi/l2/utils.ts, defi/src/liquidationsUtils/index.ts, defi/src/storeTvlInterval/computeTVL.ts
Reverts DefiLlama/defillama-server#5798
=> Revert "coins2 revert"

defi/src/constants/chainsByOracle.ts
gm llama sers
requesting your review to add a small change to one chain under pyth - from BNB to BSC
thank you
=> change bnb to bsc

defi/src/protocols/data3.ts
Update Steadefi info to better reflect current conditions
I also want to update the logo but not sure how to do it so I attached here
=> chore: update steadefi info

coins/src/adapters/index.ts, coins/src/adapters/yield/ambit-finance/index.ts
added a new adapter to return the price of the Ambit Finance AUSD stablecoin
=> adding ambit finance

coins/src/adapters/tokenMapping.json, defi/src/protocols/data3.ts, defi/src/protocols/parentProtocols.ts
add tokens to linea + add token info lynex
=> add tokens to linea + add token info lynex

coins/src/adapters/markets/curve/index.ts
Add crvUSDT, crvUSDC, crvUSDC.e Curve LPs on Arbitrum
=> Add crvUSDT, crvUSDC, crvUSDC.e

defi/src/protocols/data3.ts
description bouncebit + modifications 5546
=> description bouncebit + modifications 5546

defi/src/protocols/data3.ts, defi/src/protocols/parentProtocols.ts
add stables to childreens Prisma
=> add stables to childreens Prisma

defi/src/protocols/data3.ts
Modify Dypius Token Address, Audits & Oracle use
=> Modify Dypius Token Address, Audits & Oracle use

coins/src/adapters/tokenMapping.json
=> remove usdb from blast

defi/src/dimension-scripts/checkLastDayDerivativesUrgent.js, defi/src/dimension-scripts/checkLastDayFeesUrgent.js, defi/src/dimension-scripts/checkLastDayVolumeUrgent.js
=> add dimension API scripts

defi/src/protocols/data3.ts
Add primeETH as a child of Origin DeFi
=> feat: add primeETH to origin

defi/src/protocols/data3.ts
We've updated our Twitter Link Account. Please merge.
=> Update data3.ts and Blaster DEX correct twitter link

defi/src/protocols/data3.ts
Update token CELL :address & coingeko id
=> Update token CELL data

defi/src/protocols/data.ts
Added "Archway" to the chains array for the Balanced protocol. Balanced is now connected to Archway (https://blog.balanced.network/archway-connection/)
=> Update data.ts - Added "Archway" to the chains array for the Balanced protocol

defi/src/protocols/data3.ts
adding oracle data and link to audit(s)
=> Update data3.ts for suilend

coins/src/adapters/tokenMapping.json, defi/src/protocols/data3.ts
=> ZEND token info

defi/src/protocols/data3.ts
Added repl twitter link - https://twitter.com/Repl_fi
=> add repl twitter

defi/src/storeTvlInterval/storeNewTokensValueLocked.ts
This pull request adds TVL compression and error handling for DynamoDB writes. It compresses the TVL object and handles errors when writing to DynamoDB.
=> Add TVL compression and error handling for DynamoDB writes

coins/src/adapters/tokenMapping.json
For more information:
IBC denom: https://app.osmosis.zone/assets/PICA
Coingecko: https://coingecko.com/en/coins/picasso
=> Add PICA coin

defi/src/protocols/data3.ts
Correcting the project description
=> update Vest Exchange description

defi/src/protocols/data3.ts
Update audits status and add links to reports
=> add fyde audits

defi/src/protocols/data3.ts
Reverts DefiLlama/defillama-server#6454
=> Revert "Ton Locker Category"

coins/src/adapters/index.ts, coins/src/adapters/markets/thala/index.ts
=> [thala] add MOD-USDC market

defi/src/protocols/data2.ts, defi/src/protocols/data3.ts
Merge FX Swap to MarginX under 1 parent(MarginX)
Previous:
FX Swap (Dexes)
MarginX (Derivatives)
New:
MarginX (Dexes)
MarginX (Derivatives)
=> Rename FX Swap to MarginX DEX and update MarginX description

defi/src/adaptors/data/fees/config.ts
Reverts DefiLlama/defillama-server#6492
=> Revert "Frax amo"

coins/src/adapters/index.ts, coins/src/adapters/rwa/kuma.ts
Add pricing for KUMA protocol tokens, see https://defillama.com/protocol/kuma-protocol / https://github.com/DefiLlama/DefiLlama-Adapters/pull/8561 for more details.
=> Add KUMA protocol tokens

defi/src/protocols/data2.ts, defi/src/protocols/data3.ts
updated the website url in v2 and v3 title of A51 Finance
=> fix: updated the website url in v2 and v3 title of A51 Finance

defi/src/protocols/data3.ts
PR to remove the AU symbol from Aurelius since the token isn't live yet
=> Remove AU token symbol from Aurelius

defi/src/protocols/data3.ts
- Update orange-finance description
=> Update protocol information for Orange Finance

coins/src/adapters/tokenMapping.json, coins/src/adapters/tokenMapping_added.json
=> weekly tokens move

defi/src/protocols/data.ts
New Governance's ID:
ETH+, hyUSD, USDC+, USD3 and rgUSD
=> Add Reserve Treasury and Mainnet Governance's ID

defi/src/protocols/data3.ts
gm
requesting your review to add new protocols under Pyth oracle
TLX Finance
https://docs.tlx.fi/basics/how-leveraged-tokens-work/synthetix-perps-engine
YFX V4
https://docs.yfx.com/yfx-v4/trading/pricing-mechanism
Rollie Finance
https://docs.rollie.finance/oracle
=> add new pyth users

defi/src/protocols/data3.ts, defi/src/protocols/parentProtocols.ts
=> add NAVX token cgid

defi/src/protocols/data2.ts
Attribute Oracle Providers by chain
=> Add Oracle by Chain to Fraxlend

defi/src/protocols/data.ts
DFS Network have launched own blockchain
=> Update basic information for DFS Network

coins/src/adapters/tokenMapping.json
=> Update token CELL cgk id

coins/src/adapters/other/index.ts, coins/src/adapters/other/warlord.ts
=> feat: warlord price

defi/src/adaptors/data/protocols/config.ts
Test Ids (uni, pancake,smbswap)
=> Test Ids (uni, pancake,smbswap)

coins/src/adapters/rwa/dinari.ts
See also
- https://github.com/DefiLlama/DefiLlama-Adapters/pull/10627
=> feat: add USD+ and chains to Dinari

coins/src/adapters/tokenMapping.json, defi/src/protocols/data3.ts
This pr updates the details for amped finance following the relaunch
- The address of the token has been updated to data3.ts
- Token has been added to tokenMappings
=> Update amped finance details

coins/src/adapters/yield/pendle/index.ts, coins/src/adapters/yield/pendle/pendle.ts
Reverts DefiLlama/defillama-server#7314
=> Revert "pendle"

defi/src/protocols/data.ts
Updates the description of the ShapeShift project. The current description mentions "free" which is still accurate for transactions under $1000, but above this amount ShapeShift takes fees now. We've also added services like loans (provided through ThorChain), so we figure it's worth mentioning it too.
=> chore: update shapeshift description

defi/src/utils/normalizeChain.ts
Reverts DefiLlama/defillama-server#7322
=> Revert "fix 7310"

coins/src/adapters/rwa/dinari.ts
Add Kinto to Dinari
See also
- https://github.com/DefiLlama/DefiLlama-Adapters/pull/10769
=> feat: dinari kinto tvl

defi/src/protocols/data3.ts
Kinetix.Finance platform introduced ecosystem KAI token. Please add KAI token info to Kinetix.Finance projects. 
Token Info: https://docs.kinetix.finance/usdkai-tokenomics
=> Add KAI token to Kinetix.Finance

defi/src/protocols/data3.ts
Added Pyth as an oracle provider
=> Update Oracle Providers for Cadence Protocol

coins/src/adapters/yield/mean-finance/index.ts
We are now adding Rootstock support for Mean Finance
=> feat: add rsk to mean finance

defi/src/protocols/data3.ts
=> fix categories

defi/src/protocols/data2.ts
Add Oracle Provider for Ethereum
=> Update Fraxlend Oracle Providers 7-2-24

defi/src/adaptors/data/aggregator-derivatives/config.ts
- enable kwenta agg ppepr
- updtae
=> enable kwenta agg pperp

defi/src/adaptors/data/fees/config.ts
- enable 2024-8-18
- add parent
=> enable 2024 08 18

defi/src/protocols/data3.ts
update governanceID, audit note and audit.
=> updates for Maha.xyz

defi/src/protocols/data.ts, defi/src/protocols/data2.ts, defi/src/protocols/data3.ts
gm
adding Pyth oracle users:
Folks Finance - https://github.com/Folks-Finance/folks-finance-xchain-contracts/tree/main/contracts/oracle
LineHub Perps -  https://docs.linehub.io/linehub-products/more#enhanced-security 
(https://lineascan.build/address/0x09b573a41d389fef53cb3abeaebfdebf9a32dbaa)
=> add pyth oracle users

coins/src/adapters/liquidStaking/ifil/index.ts
Change the contract address of the Glif Infinity Pool contract, which provides the iFIL price, from V1 to V2.
https://x.com/glifio/status/1831081656780046497
=> change tartet address of iFIL #7954

defi/src/protocols/data3.ts
Updated the description by adding 'regulated'
=> return-finance

defi/src/protocols/data2.ts
Hey Llamas,
Kindly asking to update oracles for Phuture.
Implementation Details: 
Phuture uses RedStone Oracles as the primary solution for asset pricing. Phuture utilises the Pull model where the data is automatically appended to user transaction.
https://docs.phuture.finance/protocol-1/about
=> Update Oracles for Phuture.ts

defi/src/protocols/data3.ts, defi/src/protocols/parentProtocols.ts
https://github.com/DefiLlama/DefiLlama-Adapters/pull/11643#issuecomment-2352059417
=> Add parent typus finance

defi/src/protocols/data3.ts
Oracle Provider(s): Specify the oracle(s) used: adding Chronicle Oracles for Euler v2
Implementation Details: Briefly describe how the oracle is integrated into your project:
Chronicle secures for Euler:
ETH/USD
MKR/USD
wsETH/USD
USDS/USD
CBBTC/USDC
SKY/USD
SUSDS/USD
Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
ETH/USD https://etherscan.io/address/0x956C9b887cB8779140EED942fa91f51B13Bd1b86
MKR/USD https://etherscan.io/address/0x5c5B67D71559744d5d1DbB2c9C282761919A25Cf
wsETH/USD https://etherscan.io/address/0x9Ee335e15692317A4fAdb221feA0AFfe48953130
USDS/USD https://etherscan.io/address/0x6245cd4E6fef97ccc0508242135fdF2577006cfc
CBBTC/USDC https://etherscan.io/address/0xDC8af46aDF7143e58047beECA27210D6dc760721
SKY/USD …
=> Update Euler description

defi/l2/cli/backfillSingle.ts, defi/l2/cli/testL2.ts, defi/l2/storeToDb.ts
Hello
I fixed several spelling issues for a better understanding.
Br, Elias.
=> docs fix spelling issues

defi/src/protocols/data.ts
Dear DeFiLlama team,
Tokemak submits a PR updating details regarding its launch of Autopilot. Following changes were made
- Update to the description to describe the new product
- See: https://docs.tokemak.xyz/
- Update Twitter handle
- Post here: https://x.com/TokenReactor/status/1808920671134839024 as well as the banner description for the previous account pointing users to the new one
- Link to comprehensive audits page for the new system
- Adding oracles used to determine "safe" prices protecting Tokemak TVS
- Link to Docs: https://docs.tokemak.xyz/developer-docs/contracts-overview/autopool-eth-contracts-overview/autopilot-contracts-and-systems/pricing#safe-price-call-flow
- For RedStone:
- https://x.com/TokemakXYZ/status/1836834526087012382
- …
=> Update tokemak oracles, audits, twitter, desc

coins/src/adapters/tokenMapping.json
Change the address to the correct one.
=> fix TruAPT token details

coins/src/adapters/tokenMapping.json
Add USDC.e to Defiverse
- Token: https://scan.defi-verse.org/token/0x7275B8DBAF919FDDa6eE6B36F12Fd25C0F193502
- Vault: https://scan.defi-verse.org/address/0x2FA699664752B34E90A414A42D62D7A8b2702B85
=> Add USDC.e to Defiverse

defi/src/protocols/data3.ts
Added oracles used in Euler v2 markets
=> Add Redstone, Pyth and Chainlink oracles for Euler v2

defi/src/protocols/data2.ts
Hi DeFiLlama Team,
We’ve implemented a multi-oracle mechanism in our protocol to enhance the accuracy and resilience of our price feeds. As a result, we've adjusted the oracle configurations to prioritize security and stability, ensuring consistent data even during market fluctuations.
ref: https://docs.bsc.lista.org/for-developer/collateral-debt-position/multi-oracle#intro-of-resilient-oracle
If you need further details, feel free to reach out.
=> feat: conf lista oracle

coins/src/adapters/tokenMapping.json
Add following Tokens:
- fastUSD
- ssETH
- dinero
- syUSD
- seiyan
=> Update tokenMapping.json - add Sei Tokens

defi/src/protocols/data3.ts
Update Satoshi Protocol description
Thanks !!
=> update Satoshi Protocol description

coins/src/adapters/index.ts, coins/src/adapters/other/wcgUSD.ts
add wcgUSD price on base: `wcgUSD = (totalSupply / totalShares) * cgUSD`
=> add wcgUSD price on base

coins/coins2.ts, coins/package.json, coins/src/adapters/okx/constants.ts, coins/src/adapters/okx/index.ts, coins/src/adapters/okx/postgres.ts, coins/src/adapters/okx/types.ts, coins/src/adapters/okx/utils.ts, coins/src/fetchCoingeckoData.ts, coins/src/getCurrentCoins.ts, coins/src/scripts/okxMetadata.ts, coins/src/utils/missingCoins.ts
Reverts DefiLlama/defillama-server#8400
=> Revert "Revert "okx""

defi/src/protocols/data3.ts
Hey Llamas, 
Kindly asking to update the oracle for LayerBank on Linea, Scroll, Mode and zkLink Nova.
Oracle Provider(s): eOracle
Implementation Details: LayerBank uses eOracle as the primary solution for asset pricing on Linea, Scroll, Mode and zkLink Nova.
Documentation/Proof: https://docs.layerbank.finance/protocol/lending/oracles
=> LayerBank eOracle Update

defi/src/constants/chainsByOracle.ts
Added supported chains for eOracle
=> eOracle chainsByOracle update

defi/src/protocols/data3.ts
unlist APRO till APRO team is ready
=> feat: unlist apro

defi/src/protocols/data.ts
We are now adding Umbrella Network to our list of oracles
=> chore: add umbrella to oracles

defi/src/protocols/data2.ts
=> Fix Vaultcraft github handle

coins/src/adapters/rwa/midas.ts
This PR is related to https://github.com/DefiLlama/DefiLlama-Adapters/pull/12297
=> Midas RWA: add mBTC token and Base TVL

defi/src/protocols/data3.ts
gm llama sirs 
adding new protocols that rely on Pyth oracle
Limitless Exchange
https://x.com/kirkoyaa/status/1858123297788920123
https://x.com/PythNetwork/status/1857445973431300419
Swaylend
https://x.com/swaylend/status/1849428032626246032
https://docs.swaylend.com/developers/contract-methods/contract-storage
Zenolend
https://docs.zeno.finance/lending-market/price-oracle
Adrena
https://docs.adrena.xyz/technical-documentation/oracles-and-price-feeds
thank you
=> new pyth users

defi/src/constants/chainsByOracle.ts
Add Superseed, and Berachan as additional chains for Chronicle
- https://docs.berachain.com/developers/developer-tools#oracles
- https://mirror.xyz/superseedxyz.eth/2g-cWJcXjxax1pooF1ah5tUJjeUvw7lMENJpLsRj5c0
=> Add chains for Chronicle

defi/src/protocols/data3.ts
This PR updates name and description for `powpeg` fast mode option using flyover. 
https://defillama.com/protocol/powpeg
=> Update `powpeg` protocol name and description

defi/l2/test.ts
Reverts DefiLlama/defillama-server#8757
=> Revert "temp no logging"

coins/src/adapters/tokenMapping.json
Add CCP to Defiverse
- Token: https://scan.defi-verse.org/token/0x1Bd5Fc212cC1c881C67076694C134aE8cAEce3bd
- Vault: https://scan.defi-verse.org/address/0x2FA699664752B34E90A414A42D62D7A8b2702B85
- Coingecko: https://www.coingecko.com/en/coins/chain-colosseum-phoenix
Add bCCP to Defiverse
- Token: https://scan.defi-verse.org/token/0x4362Be024eFbb8C6fBcF19675224b58dFd2493Ef
- Vault: https://scan.defi-verse.org/address/0x2FA699664752B34E90A414A42D62D7A8b2702B85
- Coingecko: https://www.coingecko.com/en/coins/beta-chain-colosseum-phoenix
=> Add CCP token to Defiverse

defi/src/protocols/data3.ts
gm llama sirs
adding Satori that has integrated with the Pyth oracle
https://docs.satori.finance/perpetual-trading/index-price
thank you
=> Add-pyth-new-protocols

coins/src/adapters/bridges/index.ts, coins/src/adapters/bridges/optimism.ts, coins/src/adapters/other/distressed.ts, coins/src/adapters/solana/utils.ts, coins/src/adapters/utils/database.ts, coins/src/adapters/utils/getWrites.ts, coins/src/fetchCoingeckoData.ts, coins/src/scripts/coingecko.ts, coins/src/utils/coingeckoPlatforms.ts, coins/src/utils/processCoin.ts, common/chainToCoingeckoId.ts
Reverts DefiLlama/defillama-server#8801
=> Revert "eclipse coins "

defi/src/protocols/parentProtocols.ts
Update description for bluefin protocol
=> Update description for bluefin protocol

coins/src/adapters/rwa/fortunafi.ts
Update Fortunafi rwa with more assets
=> Update: Fortunafi (RWA) more assets

defi/src/protocols/data3.ts
Changed the number of audits for Access Protcol, the audit links were already included.
=> Access Protocol audit count fixed

coins/src/adapters/index.ts, coins/src/adapters/markets/parallelProtocol/index.ts, coins/src/adapters/markets/parallelProtocol/parallelProtocol.ts
add Parallel Protocol (docs: https://docs.mimo.capital/parallel-protocol) stablecoins price (PAR and paUSD). 
What is PAR: https://docs.mimo.capital/parallel-protocol/parallel-protocol/par
What is paUSD: https://docs.mimo.capital/parallel-protocol/parallel-protocol/par-1
=> feat: add parallel protocol stablecoins prices

defi/src/protocols/data3.ts
Added new Watchpug audit report to Sceptre Liquid protocol (id 4724)
=> Added audit to Sceptre Liquid

defi/src/protocols/data3.ts
update tako tako oracle from API3 to Pyth
=> update tako tako oracle

defi/src/protocols/data3.ts
Official source: https://x.com/Amphor_io/status/1869419216383918258
=> feat: add amphor as part of inceptionrlt post-merge

defi/src/adaptors/data/fees/config.ts
- enable hyperliquid fees
- set display name
=> enable hyperliquid fees

defi/src/protocols/data3.ts
added Pyth oracle for Echo Lending
=> added Pyth oracle for Echo Lending

coins/src/adapters/tokenMapping.json
References:
1. https://docs.stakestone.io/stakestone/developers/smart-contracts-address_stone
2. https://docs.stakestone.io/stakestone/developers/smart-contracts-address_sbtc
=> Add stakestone stone(aptos) and sbtc(aptos)

coins/src/adapters/tokenMapping.json
=> feat: add MBTC on Duckchain

coins/src/adapters/tokenMapping.json
Add token infos for SolvBTC and SolvBTC.BBN on corn/sonic/sei chains
=> Add solvbtc/solvbtc.bbn on corn/sonic/sei

defi/src/protocols/data3.ts
Updated blazing bots twitter link
=> updated blazing

defi/src/protocols/data3.ts
This PR intends to adapt the protocol data with https://github.com/DefiLlama/DefiLlama-Adapters/pull/12927
=> Adapt Pryzm Protocol with adapters change

defi/l2/test.ts
Reverts DefiLlama/defillama-server#9060
=> Revert "soneium"

defi/l2/test.ts
Reverts DefiLlama/defillama-server#9061
=> Revert "Revert "soneium""

defi/l2/test.ts
Reverts DefiLlama/defillama-server#9066
=> Revert "Revert "Revert "soneium"""

defi/l2/tvl.ts
Reverts DefiLlama/defillama-server#9101
=> Revert "eclipse tvls"

defi/src/protocols/data3.ts
Hello Team, 
updating Segment Finance description, chains, oracles, sunsetting bsc token.
Cheers, Alex
=> Update Segment Finance: adding Chains and Oracles, sunsettings bsc token

coins/src/adapters/tokenMapping.json
https://cronoscan.com/token/0xd1D7A0Ff6Cd3d494038b7FB93dbAeF624Da6f417#readContract
=> feat: list trump

defi/l2/test.ts
Reverts DefiLlama/defillama-server#9206
=> Revert "skip l2 check"

coins/src/adapters/index.ts, coins/src/adapters/yield/jeurx.ts
Add priceFeed for Superfluid Jarvis Synthetic Euro (jEURx). As jEURx = jEUR and  
1 jEUR = 1 EUR
=> Write priceFeed for jEURx.

defi/src/protocols/data3.ts
Layerbank now uses eOracle feeds on their BOB and Bsquared chain markets. 
Layerbank github repo with priceCalculator contract address https://github.com/layerbank/contracts
**BOB Mainnet** 
Price calculator : https://explorer.gobob.xyz/address/0x109F83CFC3164562B6fb1addf02Bfa65bF6f71BE
Transactions to switch price feed : 
https://explorer.gobob.xyz/tx/0x1c9feed0dd7d4ad15c90f41763503c322db0a206fb4a6f8798fa28ef8c4e4497
https://explorer.gobob.xyz/tx/0xc82fd4d611eb87fc4effb9fc4741f2d8d384f942f4b85c312a74a1675d2ec183
https://explorer.gobob.xyz/tx/0x23b3e2f6cf9b3770823d528e53f32d0134ce14adb2df423b6389fa6006fe0c74
https://explorer.gobob.xyz/tx/0x4f7d245e34fb1757df1e18d593dfae19109a15bddf1f6d30fea3fe6770311d5e
https://explorer.gobob.xyz/tx/0x59443e6a3c780e4052e057d84251d005b873071d48054433bc94514 …
=> Add eoracle to bob and bsquared for layerbank

defi/src/protocols/data3.ts
Update the audit type for Extra Finance Xlend.
=> Update the audit type for Extra Finance Xlend

defi/src/protocols/data3.ts
Hey Llamas,
Kindly asking to update oracles for Cian protocol.
https://docs.cian.app/getting-started-with-cian/yield-layer/introduction/redstone-oracles
=> Update Oracles for Cian.ts

defi/src/protocols/data3.ts
=> Update Xswap prtocol data on Crossfi chain

defi/src/protocols/data4.ts
Added oracle data to Quill Finance `id: "5685"` in `data4.ts`
=> Added oracle data to id 5685

defi/src/protocols/data2.ts
update axelar typo in protocols config
=> fix: renamed alexar to axelar 

defi/src/protocols/data2.ts, defi/src/protocols/parentProtocols.ts
- Updating the Main Description
- Editing Morpho Compound and Morpho Aave old optimizers.
=> feat(morpho): updating the main description + small edit

defi/src/protocols/data3.ts
Added oracle data to Avalon Finance in `data3.ts`
=> Added oracle data to Avalon finance

coins/src/adapters/bridges/flow.ts, coins/src/adapters/bridges/index.ts
GM,
this PR is to add Flow bridged tokens to the coins' price API
=> feat: add flow in Coin's bridges adapter

defi/src/protocols/data4.ts
Hey Llamas,
Kindly asking to update oracles for Takara on Sei.
Implementation Details: Takara is using RedStone feeds on all pools (including Sei, ISei, USDT, USDC)
https://takara.gitbook.io/takara-lend/protocol-information/security#takara-security-measures
https://app.takaralend.com/market/WSEI
=> Update Oracles for Takara.ts

coins/src/adapters/tokenMapping.json
Added mstETH mapping for Zircuit since it appears to be missing correct pricing
=> added mstETH mapping for Zircuit

defi/src/protocols/data3.ts
Hello Llamas,
Made a PR to update oracle of DefX to Pyth
https://docs.defx.com/docs/defx-product-docs/price-oracle
=> Update of DefX oracle

defi/src/protocols/data3.ts
=> update of Sobax oracle

coins/src/adapters/index.ts, coins/src/adapters/markets/0xequity/index.ts, coins/src/adapters/markets/0xequity/xequity.ts
Add price for the tokenized asset of 0xequity RWA for
Base ,Arbitrum and Units0.
=> Add 0xequity RWA token

coins/src/adapters/index.ts, coins/src/adapters/markets/0xequity/index.ts, coins/src/adapters/markets/0xequity/xequity.ts
Reverts DefiLlama/defillama-server#9453
=> Revert "Revert "Add 0xequity RWA token""

defi/.gitignore, defi/package-lock.json, defi/package.json, defi/src/api2/cache/file-cache.ts, defi/src/api2/cron-task/appMetadata.ts, defi/src/api2/cron-task/githubMetrics.ts
Added code to generate each protocol related code and store it in config/lite folder
most of the code is ported from https://github.com/DefiLlama/defillama-app/blob/main/src/api/categories/protocols/getProtocolData.tsx
=> App pregen protocol data

defi/src/adaptors/data/dexs/config.ts, defi/src/adaptors/data/fees/config.ts
=> enable 16.03

defi/src/protocols/data.ts
Hello DefiLlama team! Added oracle data to ID686 on data.ts (Yel FInance)
Sources: https://yield-enhancement-labs.gitbook.io/yield-enhancement-labs/about-yel/oracles
Thank you! :-)
=> Added oracle data to ID686 on data.ts

defi/src/protocols/data4.ts
=> Update Extended description

defi/src/protocols/data3.ts
Hi Llamas!
another PR for update on Zest Oracle
Docs
https://docs.zestprotocol.com/start/borrow/zest-protocol-borrow-overview/oracles#zest-protocol-uses-pyth
X post
https://x.com/ZestProtocol/status/1902782204121686174
=> Update of Zest Oracle

defi/src/protocols/data4.ts
Hi again!
Submitting a request to add Stork as the primary oracle for Extended
Proof: https://docs.extended.exchange/extended-resources/trading/oracle-prices
Thanks!
=> Add Stork as oracle for Extended

defi/src/protocols/data3.ts
Hey guys, 
Requesting to add Stork as the oracle for Blitz Exchange
Proof: https://docs.blitz.exchange/basics/pricing-oracles 
Thanks!
=> Add Stork as primary oracle for Blitz

defi/src/protocols/data4.ts
Hey Llamas, 
Requesting to add Stork as the oracle for Citrex
Proof: https://citrex.gitbook.io/citrex-markets/citrex-markets/funding-and-pricing 
Thanks!
=> Add Stork as oracle for Citrex

coins/src/adapters/tokenMapping.json
=> add lfbtc-cian-eth

defi/src/constants/chainsByOracle.ts
Hi
as discussed via discord,
https://discord.com/channels/823822164956151810/823822533974425621/1353742602486157436
added some chains missing for Pyth, 
also noticed extra "" on Switchboard - Sonic, and edited it as well
might add more if i see other chains missing as well
=> Add chains on oracles

defi/src/protocols/data4.ts
To let StableKitty be shown in this page: <https://defillama.com/forks/Curve>
=> feat: update StableKitty's forkedFrom to "Curve"

defi/src/protocols/data2.ts
Hi
Updated oraclesbreakdown for Aries Markets
Proof links are indicated
=> Update of oraclesbreakdown

defi/src/protocols/data3.ts
Bonzo is using Chainlink oracles to secure their HBAR and USDC markets:
Sources:
https://docs.bonzo.finance/hub/developer/oracles/chainlink
http://bonzo.finance/blog/bonzo-finance-has-integrated-the-chainlink-standard-for-verifiable-data-on-hedera
=> Added oracles to ID5287 on data3.ts

defi/src/adaptors/data/dexs/config.ts, defi/src/adaptors/data/fees/config.ts
Reverts DefiLlama/defillama-server#9609
=> Revert "disable agni"

defi/src/protocols/data4.ts
Hi,
Made a PR to update oracle for Dahlia
=> Update Dahlia oracle

defi/src/protocols/data3.ts
Hi! Updating some oracles, this time for `id:3344` in `data3.ts`
Thank you. :-)
=> Added oracles to fx Protocol

defi/src/protocols/data3.ts
Hi!
Updating a new oracle, this time for` ID: 3344` on `data3.ts`. 
Thank you! :-)
=> Update ReactorFusion Oracles

defi/src/protocols/data4.ts
Hi,
Made a PR to update oracle for Vicuna Finance
=> Update Vicuna Finance oracle

coins/src/adapters/index.ts, coins/src/adapters/rwa/xu3o8.ts
- Added xu3o8 token in rwa. Fetched token price from the pool and token symbol and decimals from token's contract.
1. `cd coins && npm install`
2. ` ts-node src/test.ts xu3o8`
**output**
==== Testing xu3o8 ====
Token Symbol xU3O8
Token price 4.057851258161936
Token Decimals 18There's an expected failure while writing to DefiLlama DB
There's an expected failure while writing to defiLlama server which is fine.
```
unhandled rejection Error [ConfigError]: Missing region in config
at Request.VALIDATE_REGION (/Users/bassemabdelazim/workspace/node_modules/aws-sdk/lib/event_listeners.js:128:47)
```
=> Added xu3o8 token in rwa.

defi/src/protocols/data3.ts
Hi RealDealShaman,
Submitting a request to add Stork as an oracle for Paradex.
Thanks!
=> Add Stork as oracle for Paradex

defi/src/protocols/data3.ts
Hey RealDealShaman,
PR for adding Stork as the oracle for Perennial.
Thanks!
=> Add Stork as oracle for Perennial

defi/src/protocols/data4.ts
Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.): Redstone
Implementation Details: Briefly describe how the oracle is integrated into your project: We use Redstone's pull oracle on AO to fetch prices for operations such as liquidations in the lending protocol via the controller.
Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage: https://docs.liquidops.io/protocol/oracle
=> Add LiquidOps' oracle to DefiLlama

defi/src/protocols/data3.ts
Hi RealDealShaman,
Submitting a PR for the oraclesbychain with Meridian's updated docs
Thanks!
=> Add oracles to Meridian

defi/src/constants/chainsByOracle.ts
Hi, 
Updated Hyperliquid chain to Hyperliquid L1
=> Update chains By Oracle

defi/src/protocols/data3.ts
Hi @realdealshaman!
Added an oracle to Avalon USDa. It had none attributed. 
Thank you :-)
=> Added oracle data to id 5312 in data3.ts

coins/src/adapters/tokenMapping.json
Added 2 more tokens to add on the LUKSO chain.
=> Adding tokens to track on LUKSO

defi/src/protocols/data2.ts
Hi !
Made an update on Mole Oracle!
Proof on the PR 
Thank you
=> Update of Mole Oracle

coins/src/adapters/tokenMapping_added.json
WAVES-Waves-PPT - wrapped WAVES from Waves blockchain by PepeTeam (dex.pepe.team). Proof of reserves https://bridge.pepe.team/tokens/WAVES-Waves-PPT
UNIT0 - wrapped UNIT0 token by Units team (https://wavesbridge.io/bridge?from=WAVE&to=UNIT&asset=UNIT0), asset info https://wavescap.com/asset/UNIT0/info
=> Add WAVES + UNIT0

defi/src/protocols/data3.ts
Add Chronicle as primary oracle for Jigsaw
Chronicle powers the following oracles:
WETH/USD - https://etherscan.io/address/0xe9473c1DA9E5c91f90fEc670290E3fEFe32fB9F5#code
RUSD/USD - https://etherscan.io/address/0xb710FdCd2566B0D70ED729882799BaCF4e72aEb8
WSTETH/USD - https://etherscan.io/address/0x99eFCD0AdAEb5d18bF137A4b703bc50001121097
WEETH/USD - https://etherscan.io/address/0xcb0a29A3C996B2C1d1F0c3BDd94028712FbE2E89
WSTETH/USD - https://etherscan.io/address/0x99eFCD0AdAEb5d18bF137A4b703bc50001121097
WEETH/USD - https://etherscan.io/address/0xcb0a29A3C996B2C1d1F0c3BDd94028712FbE2E89
WBTC/USD - https://etherscan.io/address/0xC0879B122e861b43E79041486624fc98A4132D72
USDC/USD - https://etherscan.io/address/0xB349eb6B171d56ff3A98C3460A9Eb80975F0972d
USDT/USD - …
=> Update  Jigsaw description

defi/src/protocols/data4.ts
We updated the description about us, and we don't know how to update our logo.
Please tell us how to do it or help us update our logo.
here is the new picture
Thank you!
=> Vanilla Finance Update data4.ts

defi/src/protocols/data.ts
Hi! @realdealshaman, added the ´oracle´ field to id587 (Maple Finance) in ´data.ts´
Thank you!
=> Added oracle field to id587 in data.ts

coins/src/adapters/rwa/midas.ts
Corresponding PR in DefiLlama-Adapters: https://github.com/DefiLlama/DefiLlama-Adapters/pull/14660/
=> Midas RWA: add mTBILL and mBTC on rootstock

defi/src/protocols/data2.ts
Reverts DefiLlama/defillama-server#9876
=> Revert "prdt"

defi/src/protocols/data2.ts
Hey @realdealshaman Adding in Stork as a fallback oracle for Orderly.
Thanks!
=> Add Stork as a fallback oracle for Orderly

defi/src/protocols/data4.ts
Hi
as indicated, made a PR for HyperPie oracle
Thanks!
=> Update of HyperPie Oracle

coins/src/adapters/tokenMapping.json
Change the coingecko id of USDC.e from usdc to usd-coin
=> update usdc.e coingecko id for rbn

defi/src/protocols/data4.ts
Updated Clutch token address and website url
=> Update: Clutch Market new address and url

coins/src/adapters/tokenMapping.json
Add price for token: lisk:0x9bfa177621119e64cecbeabe184ab9993e2ef727
=> add M-BTC token price map on lisk

coins/src/adapters/index.ts, coins/src/adapters/rwa/pareto.ts
Track Pareto's credit vaults LP tokens prices
=> NEW: Pareto credit CVs prices

defi/src/protocols/data.test.ts, defi/src/protocols/data.ts, defi/src/protocols/data2.ts, defi/src/protocols/data3.ts, defi/src/protocols/data4.ts
Reverts DefiLlama/defillama-server#10025 until i fix the test
=> Revert "oraclesBreakdown modify and add check chain"

coins/src/adapters/tokenMapping.json
- Set price source for the USDa and sUSDa on Movement network
=> feat: add USDa and sUSDa on Movement

coins/src/adapters/index.ts, coins/src/adapters/yield/reya/abi.json, coins/src/adapters/yield/reya/index.ts, coins/src/adapters/yield/reya/reya.ts
Adding 2 tokens from Reya Chain that earn yield. Let me know if the proposed code works.
The goal is to be able to later list them, with correct prices, in TVL adapters
=> adding Reya yield token prices

defi/src/protocols/data4.ts
Hey RealDealShaman,
Updating oracle breakdown for Mystic Finance
Best,
Brian
=> Add Stork as oracle for Mystic

defi/src/protocols/data3.ts
Hey,
Adding Hemi chain to Satoshi Protocol including eOracle as the primary oracle.
Docs: https://docs.river.inc/outro/oracle
Thanks!
=> Update Satoshi Protocol (River) on Hemi

defi/src/protocols/data4.ts
Stork lists eOracle as one of the oracles it uses for its lending markets (https://docs.solera.market/overview/editor/oracles), please help add this and let us know if you have any questions.
=> add eOracle to Solera oracle

coins/src/adapters/tokenMapping.json
=> add dchainmainnet WETH

defi/src/api2/cron-task/appMetadata.ts, defi/src/utils/normalizeChain.ts
current behavior is indeterminisitc, 
returns slug form of the chain label if chainMap contains given chain
else returns chain display name (with first char capitailized)
=> Fix chain label returned by appMetadata

defi/src/protocols/data2.ts, defi/src/protocols/data4.ts
Hi @realdealshaman submitting a PR for Stork being added as the primary oracle for Rysk
=> Add stork oracle rysk

defi/src/protocols/data4.ts
logo : https://github.com/DefiLlama/icons/pull/2221
index : https://github.com/DefiLlama/DefiLlama-Adapters/pull/15515
=> feat: added cbxrp

defi/src/protocols/data2.ts, defi/src/protocols/data4.ts
Source : https://x.com/xStocksFi/status/1942192950882259303 and https://x.com/xStocksFi/status/1939761143922532548?t=vF7ER9vvW-2Rrm6cNbcU6A&s=19
=> Add oracle for xstocks and dead url true for gmd protocol

defi/src/api2/cache/index.ts, defi/src/api2/cron-task/index.ts, defi/src/api2/utils/craftProtocolV2.ts, defi/src/getCategories.ts, defi/src/getCategoryChartByChainData.ts, defi/src/getChains.ts, defi/src/getForks.ts, defi/src/getOracles.ts, defi/src/getProtocols.ts, defi/src/getSimpleChainDataset.ts, defi/src/protocols/data/index.ts, defi/src/protocols/data1.ts, defi/src/protocols/types.ts, defi/src/storeGetCharts.ts, defi/src/storeLangs.ts, defi/src/types.ts, defi/src/utils/date.ts, defi/src/utils/excludeProtocols.ts, defi/src/utils/getProtocolTvl.ts, defi/src/utils/normalizeChain.ts
=> Fix tags route

defi/src/protocols/data4.ts
https://github.com/DefiLlama/DefiLlama-Adapters/issues/15598
=> fixed audit link of granite protocol

coins/src/adapters/yield/yearn/abiRegistry.json, coins/src/adapters/yield/yearn/abiVaultV3.json, coins/src/adapters/yield/yearn/index.ts, coins/src/adapters/yield/yearn/yearnV3.ts
Implement coins adapter to fetch Yearn V3 vaults. It follows the same flow and output as [Yearn V2 adapter](https://github.com/DefiLlama/defillama-server/blob/master/coins/src/adapters/yield/yearn/yearnV2.ts).
=> feat: coins adapter for yearn v3

coins/src/adapters/tokenMapping.json
=> Add CIAN FBTC on MOVE

defi/src/protocols/data4.ts
Docs updated over https://rezerve.gitbook.io/protocol/security/oracles
=> Updated description for Rezerve and set DIA as our primary oracle

defi/src/protocols/data1.ts
Hi again DefiLlama team! Mento is officially using Chainlink to secure the protocol. You can find more information about it here:
https://docs.mento.org/mento/overview/core-concepts/oracles-and-price-feeds#oracle-providers
https://www.mento.org/blog/mento-adopts-the-chainlink-data-standard-to-power-decentralized-stablecoins
=> Updated Mento's oracles

defi/src/protocols/data3.ts
Update Lucidly Finance protocol description on Defillama
=> feat: update Lucidly protocol description

defi/src/protocols/data4.ts
=> :art: add almanak audit

defi/src/protocols/data3.ts
Hi @realdealshaman Chainlink is now the primary oracle for Thala!
You can find more information here: https://docs.thala.fi/overview/move-dollar-mod/oracles#chainlink
And the official announcement here: https://x.com/ThalaLabs/status/1961217234988089815
=> Updated thala oracles

defi/src/protocols/data3.ts
Hi DefiLlama team! 
Added oracle to UFarm Digital
Proof: https://ufarm.digital/blog/all-articles/scaling-ufarm-with-quex
=> Add Quex oracle to UFarm Digital

coins/src/adapters/markets/crosscurve/index.ts
Now the price is calculated for all synths and LP tokens used in CrossCurve
=> feat: enhance crosscurve adapter

defi/src/protocols/data4.ts
=> update brownfi twitter

defi/src/protocols/data4.ts, defi/src/protocols/parentProtocols.ts
1. "DefiTuna Dex" renamed to "DefiTuna AMM"
2. Audit links added to DefiTuna AMM and Lending
3. DefiTuna parent project description changed (it was a copy of the previous project description)
=> DefiTuna metadata

coins/src/adapters/tokenMapping.json
Add EL token to tokenMapping.json for Soneium network
=> Add EL token to tokenMapping.json for Soneium network

defi/src/protocols/data3.ts
Updated the oracle breakdown to reflect that we are using DIA oracles for some assets.
=> Update data for Zest Protocol: added DIA to oracles

defi/src/protocols/data4.ts
Please can we use this logo thanks
=> Description tweak + logo

defi/src/protocols/data2.ts
Updating the Primary Oracle of Compound V3 Mantle Market for USDe
Proof: https://github.com/compound-finance/comet/pull/939/files#diff-05f369cb54fde0e943753c64020a6d9a3f81e4da07141b341bfc595cc9d9b30d
=> update CompoundV3 - Mantle - Oracle - USDe Market

coins/src/scripts/coingecko.ts, coins/src/utils/getCoinsUtils.ts, defi/src/rwa/protocols.ts
Reverts DefiLlama/defillama-server#10736
=> Revert "CG edits "

defi/src/rwa/index.ts
Reverts DefiLlama/defillama-server#10751
=> Revert "apikey"

defi/src/protocols/data3.ts
Updated Arrow Markets description in its own standalone pr. Issue was raised here: https://github.com/DefiLlama/DefiLlama-Adapters/issues/15888
=> Updated Arrow Markets description

coins/src/adapters/index.ts, coins/src/adapters/markets/goblin.ts, coins/src/adapters/tokenMapping.json, coins/src/adapters/yield/misc4626/tokens.json, defi/l2/constants.ts
- Goblin Aptos Coins 
- Remove Osmosis from Bridged dashboard
- Token mappings
=> 7 Oct Commits
