src/protocols/data.ts

Changes:
- Added token address
- Added token symbol
- Added coingecko id

update solfarm info

---

src/protocols/data.ts

See: https://www.coingecko.com/en/coins/sunny-aggregator

Adds Sunny Aggregator's CoinGecko market ID

---

src/nfts/collections.ts

Add logo to be displayed on frontend. Sourced from API response from OpeanSea

Add logo to nft collections

---

src/protocols/data.ts

fix lobis information

---

src/protocols/data.ts

added cmcID on tranquil finance

added cmcID on tranquil finance

---

src/protocols/data.ts

update float capital

---

src/protocols/data.ts

Morpheus Swap description update

Morpheus Swap description update

---

src/protocols/data.ts

add audit links to stader

---

src/protocols/data.ts

add information

---

defi/src/protocols/data.ts

change mmo finance to mmo optimizer

change mmo finance to mmo optimizer

---

defi/src/protocols/data.ts

fix MM optimizer name

---

defi/src/protocols/data.ts

adding audit link for viperswap

adding audit link for viperswap

---

defi/src/protocols/data.ts

so https://007vasy.github.io/ connects well

fixing typo

---

defi/src/protocols/data.ts

add audit link for stackswap

---

defi/src/protocols/data.ts

add twitter for mdex

---

defi/src/protocols/data.ts

update description for cook finance

update description for cook finance

---

defi/src/protocols/data.ts

add description xdao

---

defi/src/protocols/data.ts

changing website/twitter url for multichain

changing website/twitter url for multichain

---

defi/src/protocols/data.ts

add audit bosswap

---

defi/src/protocols/data.ts

add audit unite finance

---

defi/src/protocols/data.ts

add audit to farmersonly

---

defi/src/protocols/data.ts

adding new link website sentre

adding new link website sentre

---

defi/src/cli/backfillDexVolumes/calcAllDailyBreakdownVolume/calcAllDailyBreakdownVolume.test.ts
defi/src/cli/backfillDexVolumes/calcAllDailyBreakdownVolume/index.ts
defi/src/cli/backfillDexVolumes/calcAllHourlyBreakdownVolume/calcAllHourlyBreakdownVolume.test.ts
defi/src/cli/backfillDexVolumes/calcAllHourlyBreakdownVolume/index.ts
defi/src/cli/backfillDexVolumes/calcAllMonthlyBreakdownVolume/calcAllMonthlyBreakdownVolume.test.ts
defi/src/cli/backfillDexVolumes/calcAllMonthlyBreakdownVolume/index.ts
defi/src/cli/backfillDexVolumes/calcAllVolumes/calcAllVolumes.test.ts
defi/src/cli/backfillDexVolumes/calcAllVolumes/index.ts
defi/src/cli/backfillDexVolumes/fixtures.ts
defi/src/cli/backfillDexVolumes/index.ts
defi/src/dexVolumes/dexVolume.types.ts
defi/src/dexVolumes/dexVolumeRecords.ts

- calcAllDailyBreakdownVolume and test
- calcAllHourlyBreakdownVolume and tests
- calcAllMonthlyBreakdownVolume and tests

Adding composability of volume by product

---

defi/src/protocols/data.ts

audit link + cm id

---

defi/src/protocols/data.ts

beefy new category

---

defi/src/protocols/data.ts

new category juststables

---

defi/src/protocols/data.ts

enterdao category

---

defi/src/protocols/data.ts

superfluid category

---

defi/src/protocols/data.ts

tomb finance category

---

defi/src/protocols/data.ts

artemis new category

---

defi/src/protocols/data.ts

ocean protocol category

---

defi/src/protocols/data.ts

deri-protocol new category

---

defi/src/protocols/data.ts

badger dao new category

---

defi/src/protocols/data.ts

hector dao to hector finance

---

defi/src/protocols/data.ts

parasset category

---

defi/src/protocols/data.ts

thales new description

---

defi/src/protocols/data.ts

lizard exchange description

---

defi/src/protocols/data2.ts

update claimswap info

---

defi/src/protocols/data.ts

add audit babylon

---

defi/src/protocols/data.ts

hop protocol category

---

defi/src/protocols/data2.ts

logo swim data

---

defi/src/protocols/data2.ts

add audit baksdao

---

defi/src/protocols/data.ts

dydx cmc id

---

defi/src/protocols/data.ts

update chains fantohm + audit links

update chains fantohm + audit links

---

defi/src/protocols/data.ts

Based Finance add audit

---

defi/src/protocols/data.ts

update module loop finance

---

defi/src/protocols/data.ts

update description integral protocol

update description integral protocol

---

defi/src/protocols/data.ts

new module zeus finance

---

defi/src/protocols/data2.ts

audit links goodghosting

---

defi/src/protocols/data.ts

add fantom network to alchemix

add fantom network to alchemix

---

defi/src/protocols/data.ts

add chains to cbridge

---

defi/src/protocols/data2.ts

fix error server poly network , remove elrond

fix error server poly network , remove elrond

---

defi/src/protocols/data2.ts

the real fix

---

defi/src/utils/normalizeChain.ts

missing neo3 only

---

defi/src/protocols/data2.ts

audit link toxicdeer

---

defi/src/protocols/data.ts

audit links to reverse

---

defi/src/protocols/data.ts

add audit links to looksrare

---

defi/src/protocols/data2.ts

add audit link to bendao

---

defi/src/protocols/data.ts

website link perpetual

---

defi/src/utils/normalizeChain.ts

Listing starcoin chain

---

defi/src/protocols/data.ts

new tweet integral

---

defi/src/protocols/data2.ts

mytrade website link

---

defi/src/protocols/data2.ts

fix gecko id

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts

update kagla and revest finance

update kagla and revest finance

---

defi/src/utils/normalizeChain.ts

change matic to polygon

---

defi/src/protocols/data2.ts

remove address tangent

---

defi/src/utils/normalizeChain.ts

remove multivac chain

---

defi/src/utils/normalizeChain.ts

add multivac chain

---

defi/src/protocols/data2.ts

update descriptio for VAX

---

defi/src/protocols/data.ts

pnetwork fix

---

defi/src/protocols/data.ts

add audit link sherlock

---

defi/src/protocols/data2.ts

fix address

---

defi/src/protocols/data2.ts

fix acala dollar

---

defi/src/protocols/data.ts

remove heco chain from O3 Swap

remove heco chain from O3 Swap

---

defi/src/protocols/data.ts

fix website links kavas

---

defi/src/protocols/data.ts

Change Angle category from Lending to CDP, which reflects better the main Angle use case (stablecoin). 
Change Angle description to reflect the deployment of Angle Borrow module.

Angle metadata update

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts

fix pink and deep

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts

Reverts DefiLlama/defillama-server#507

Revert "fix pink and deep"

---

defi/src/protocols/data2.ts

- Add astarfarm audit certification

Fix astarfarm audit information

---

defi/src/protocols/data2.ts

add parentprotocol to izumi swap

add parentprotocol to izumi swap

---

defi/src/protocols/data2.ts

add izumi tab

---

defi/src/protocols/data.ts

list whaleloans

---

defi/src/protocols/data.ts

change name on data.ts

---

defi/src/protocols/data.ts

fix sun error

---

defi/src/protocols/data2.ts

Adding audit link for Humble version 2

Add v2 audit

---

defi/src/protocols/data.ts

This contains the updated description and audit status for protocol: Brahma.fi

ft: brahma-update

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts

add parent protocol waterfall

---

defi/src/protocols/data2.ts

logo dxsale

---

defi/src/protocols/data2.ts

Hi, since our platform is not limited to Yield, we would like to change the category name as Defi.

change ALEX category

---

defi/src/protocols/data2.ts

add address

---

defi/src/protocols/data2.ts

change twitter

---

defi/src/protocols/data2.ts

description update kujira

---

defi/src/protocols/data.ts

fix data.ts error

---

defi/src/protocols/data.ts

fix category CompliFi

---

defi/src/protocols/data2.ts

audit number

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

group pods protocol

---

defi/src/protocols/data2.ts

fix server

---

defi/src/protocols/data.ts

new url uniswap

---

defi/src/protocols/data2.ts

fix address quasarswap

---

defi/src/protocols/data2.ts

change module name

---

defi/src/protocols/data.ts

add audit alpaca

---

defi/src/utils/normalizeChain.ts

fix litcoin and doge cg id

---

defi/src/protocols/data2.ts

new category

---

defi/src/protocols/data.ts

add address wallet for saddle finance

add address wallet for saddle finance

---

defi/src/protocols/data2.ts

remove carthage

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts

remove duplicated sushiswap forks

remove duplicated sushiswap forks

---

defi/src/protocols/data2.ts

change category apex protocol

---

defi/src/protocols/data2.ts

PR to expand the Matter Defi protocol description. Added one extra paragraph. 💯

Update Matter Defi protocol description

---

defi/src/protocols/data.ts

Hi.
We'd like to amend our protocol category.
We are a yield aggregator, not a yield farm.
Changed category from: "Yield" to "Yield Aggregator"
Thanks!

Protocol: Vaporwave - Update category 

---

defi/src/utils/normalizeChain.ts

add OP coingecko/cmid

---

defi/src/protocols/data.ts
defi/src/protocols/parentProtocols.ts

parent protocol

---

defi/src/protocols/data.ts

remove category

---

defi/src/protocols/data2.ts

cg id mm finance polygon

---

defi/src/protocols/data2.ts

Announcement: https://twitter.com/ToucanProtocol/status/1557397337722327040

Add Celo chain in Toucan info

---

defi/src/protocols/parentProtocols.ts

add parent protocol mm finance

add parent protocol mm finance

---

defi/src/protocols/data2.ts

metf parent

---

defi/src/protocols/data2.ts

fix last commit

---

defi/src/protocols/data2.ts

replace audit link

---

defi/src/protocols/data.ts

Changed previous broken audit link to the Bancor v2.1 audit list url.

Updated audit link for Bancor

---

defi/src/protocols/data.ts

Unlist rubic while fixing error

Unlist rubic while fixing error

---

defi/src/protocols/data2.ts

fix pancakeswap forks

---

defi/src/protocols/data2.ts

yearn forks

---

defi/src/protocols/data.ts

category brinc

---

defi/src/protocols/data.ts

Change category ramp

---

defi/src/protocols/data2.ts

change category autobark

---

defi/src/protocols/data2.ts

fix startswap

---

defi/src/protocols/data2.ts

fix description

---

defi/src/protocols/data2.ts

fix starswap startcoin to

---

defi/src/protocols/data2.ts

Fix starcoin explorer

---

defi/src/protocols/data2.ts

category liquid

---

defi/src/protocols/data2.ts

fix logo gard

---

defi/src/storeLiquidations.ts

compound subgraph issa down
ref:
https://twitter.com/compoundfinance/status/1564695152626655234
https://twitter.com/ChainLinkGod/status/1564823443920457729

[hotfix] [liquidations] disable compound

---

defi/src/protocols/data2.ts

add description bnbplay

---

defi/src/protocols/data2.ts

add description

---

defi/src/protocols/data2.ts

remove fork information

---

defi/src/protocols/data.ts

new description

---

defi/src/protocols/data2.ts

fix twitter handler

---

defi/src/protocols/data2.ts

small change wan bridge

---

defi/src/protocols/data2.ts

category metavault

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

add parentchild compound

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

small change compound

---

defi/src/protocols/parentProtocols.ts

Fix value parentProtocol

---

defi/src/protocols/data2.ts

Add audit link

---

defi/src/protocols/data.ts

Update thorchain website

---

defi/src/protocols/data.ts

update oracle and audit for robo-vault

update oracle and audit for robo-vault

---

defi/src/protocols/data.ts

change category robo

---

defi/src/protocols/data2.ts

add audit link capricorn

---

defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

fix parent sushi

---

defi/src/protocols/data.ts

fix sushi ParentProtocol

---

defi/src/dexVolumes/dexAdapters/config.ts

enable energiswap, stellaswap and wagyswap dex

enable energiswap, stellaswap and wagyswap dex

---

defi/src/dexVolumes/dexAdapters/config.ts

enable lif3-swap and swappi

---

defi/src/protocols/data2.ts

delisted gard

---

.github/workflows/coins.yml
coins/package-lock.json
coins/package.json
coins/serverless.yml
coins/src/getCurrentCoins.ts
coins/src/getHistoricalCoins.ts
coins/src/utils/missingCoins.ts
defi/env.js

not ready for merge, need to add the secret for `MISSING_COINS_DB_PWD`

store missing coins in sql db

---

defi/src/protocols/data2.ts

fix tomb finance forks

---

defi/src/protocols/data2.ts

add info numisme

---

defi/src/protocols/data2.ts

twitter link taiga

---

defi/src/protocols/data.ts

update info impermax

---

defi/src/protocols/data2.ts

Update address green planet

---

defi/src/protocols/data.ts

change website link USD+

---

defi/src/protocols/data.ts

audit link psyoptions

---

defi/src/protocols/data.ts

Change origin dollar category

---

defi/src/protocols/data2.ts

An extensive audit by the TechRate was conducted for [Metavault.Trade](http://metavault.trade/) core smart contracts. We've added an audit link to protocol info.

Added Metavault.Trade smart contract auditing report.

---

defi/src/protocols/data2.ts

Fix parent protocol izumi

---

defi/src/dexVolumes/dexAdapters/config.ts

stellarx
ultronswap
humble-defi
pact
algofi
saddle-finance

enable: titano-swych

---

defi/src/protocols/data.ts

Pull request to update information of LeonicornSwap, ID: 923.

Update LeonicornSwap Data

---

defi/src/protocols/data2.ts

fix number audit goodgosting

---

defi/src/dexVolumes/dexAdapters/config.ts

enable elk

---

defi/src/protocols/data.ts

Francium is integrating Pyth as its oracle. Kindly add them under Pyth, thank you sirs
https://twitter.com/Francium_Defi/status/1581086372211089410?s=20

Update Oracle for Francium

---

defi/src/protocols/data2.ts

fix logo handle fi perps

---

defi/src/protocols/parentProtocols.ts

Change Mycelium (part 1)

---

defi/src/protocols/data2.ts

add token address to real protocol

add token address to real protocol

---

defi/src/protocols/data2.ts

description granary

---

defi/src/protocols/data2.ts

updating description and audit properties

update versedex description and audits

---

defi/src/protocols/data2.ts

description spin

---

defi/src/protocols/data2.ts

Update token Governance of sealightswap ( I'm the owner )

Token Address Update

---

defi/src/protocols/data2.ts

pangea swap and sealightswap (2 days ago) part 1

pangea swap and sealightswap (2 days ago) part 1

---

defi/src/dexVolumes/dexAdapters/config.ts

Relist DEXes (tetu , meusliswap) + update name pangea-swap

Relist DEXes (tetu , meusliswap) + update name pan

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

Tetu Changes + ParentProtocol

---

defi/src/dexVolumes/dexAdapters/config.ts

enable 4swap

---

defi/src/protocols/data2.ts

There seems to be a miscommunication from our end so would like to request your help in removing Liquid Swap under Pyth.
Thank you sirs

Remove Liquid Swap from Pyth

---

defi/src/protocols/data2.ts

Change protocol name AUX

---

defi/.gitignore
defi/src/adaptors/cli/runGetOverview.ts
defi/src/adaptors/cli/runStoreDexVolume.ts
defi/src/adaptors/data/incentives/config.ts
defi/src/adaptors/data/incentives/index.ts
defi/src/adaptors/data/index.ts
defi/src/adaptors/db-utils/adaptor-record.ts
defi/src/adaptors/handlers/storeAdaptorData/helpers.ts
defi/src/cli/buildRequires.ts

Also now its allowed to store objects

Add support for incentives

---

defi/src/protocols/data.ts

delist xdao (while is being fixed)

delist xdao (while is being fixed)

---

defi/src/protocols/data.ts

list xdao again

---

defi/src/protocols/data2.ts

argo audit link

---

defi/src/dexVolumes/dexAdapters/config.ts

enable wanswap-dex

---

defi/src/protocols/data2.ts

update audit link verse

---

defi/src/protocols/data.ts

add audit link port finance

---

defi/src/protocols/data2.ts
defi/src/utils/normalizeChain.ts

the fix ?!!

---

defi/src/protocols/data.ts

change address yokai swap

---

defi/src/utils/normalizeChain.ts

updated canto chain + add to cosmos category

updated canto chain + add to cosmos category

---

defi/src/protocols/data.ts

-changed URL
-changed audit and added one other

Update Gamma website and audits

---

defi/src/protocols/data2.ts

new address sphere finance

---

defi/src/protocols/data2.ts

update information from sphere

update information from sphere

---

defi/src/protocols/data.ts

delist xdao

---

defi/src/protocols/data2.ts

update info OPX finance

---

defi/src/protocols/data.ts

change category yapeswap

---

defi/src/protocols/data2.ts

replace address woofi

---

defi/src/protocols/data2.ts

update information orderly

---

defi/src/adaptors/data/helpers/generateProtocolAdaptorsList.ts

Reverts DefiLlama/defillama-server#1373

Revert "Fix chains data list"

---

defi/src/adaptors/data/dexs/config.ts

enable goosefx dex

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

remove parentProtocol Yield Yak short-term solut

remove parentProtocol Yield Yak short-term solut

---

defi/src/protocols/data2.ts

change category sentiment

---

defi/src/protocols/data2.ts

undo last commit

---

defi/src/protocols/data2.ts

add audit links to sentiment

---

defi/src/protocols/data2.ts

add audit link aries market

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

enable parentProtocol Yield Yak

enable parentProtocol Yield Yak

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts

audit link index and category exin

audit link index and category exin

---

defi/src/protocols/data2.ts

missing epoch

---

defi/src/protocols/data.ts

update info tetu

---

defi/src/protocols/data2.ts

Changes include the category, chains, and audit links.

Update Aperture Finance metadata

---

defi/src/protocols/data2.ts

update cake defi description

---

defi/src/protocols/data2.ts

update category elyfi

---

coins/src/adapters/yield/mean-finance/index.ts
coins/src/adapters/yield/mean-finance/mean-finance.ts

We are now adding support for ethereum tokens, for mean finance

feat: add mean finance ethereum

---

defi/src/protocols/data2.ts

add more info to abel finance

---

defi/src/protocols/data.ts

unlisted padswap

---

defi/src/protocols/data.ts

list pad again + delist wheat protocol

list pad again + delist wheat protocol

---

defi/src/protocols/data2.ts

fix category woo-x

---

defi/src/protocols/data2.ts

update audit rage trade

---

defi/src/protocols/data2.ts

Refer to the latest addition of pETH

Update JPEGd description

---

defi/src/protocols/data2.ts

change category rage trade

---

defi/src/protocols/data.ts

Cozy uses UMA as an oracle. This PR adds Cozy to UMA's TVS.

Update Cozy Finance for UMA as oracle

---

defi/src/storeLiquidations.ts

The angle adapter seems to be causing issues.

[liquidations] temporarily exclude angle

---

defi/src/adaptors/data/fees/config.ts

eanble 0vix

---

defi/src/protocols/parentProtocols.ts

update description neopin

---

defi/src/protocols/data2.ts

small change phemex

---

defi/src/protocols/data2.ts

category polytrade

---

defi/src/protocols/data2.ts

change polytrade address

---

defi/src/protocols/data2.ts

add Y2K token address

---

defi/src/protocols/data2.ts

Enable Optitude Finance

---

defi/src/utils/normalizeChain.ts

fix server !?

---

defi/src/protocols/data2.ts

change category genius yield

---

defi/src/protocols/data2.ts

Add token address pangea swap

---

defi/src/protocols/data2.ts

change category opx

---

defi/src/protocols/data.ts

Hegic information

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts

add oracles links

---

defi/src/protocols/data2.ts

new category messina

---

defi/src/protocols/data2.ts

add tvl adapter for bluemove

---

defi/src/protocols/data.ts

add parentProtocol pandaswap

---

defi/src/protocols/data.ts

change category deri protocol

---

defi/src/protocols/data2.ts

added audit link to the FairFi project

added audit link to fairfi project

---

coins/src/adapters/other/distressedAssets.ts

ADD grv distressedAssets

---

coins/src/adapters/other/distressedAssets.ts

add gvr (eth network)

---

defi/src/protocols/data2.ts

module kujira orca

---

defi/src/protocols/data2.ts

add parentProtocol kujira orca

add parentProtocol kujira orca

---

defi/src/protocols/data2.ts

audit links level finance

---

defi/src/protocols/parentProtocols.ts

Kujira final

---

defi/src/protocols/data.ts

remove echlon guru

---

defi/src/protocols/data2.ts

fix avax error

---

defi/src/protocols/data.ts

remove chains barnbridge

---

defi/src/protocols/data2.ts

delist beth while fix it

---

defi/src/protocols/data.ts

remove eth from mirror

---

defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

remove timeless parent

---

defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

timeless parent

---

defi/src/liquidationsUtils/index.ts

my keybod must hab jammed or sumting to hab dis bug happen reeeeee

fix ze dumbest bug eva reeeee

---

coins/src/adapters/markets/jarvis/jarvis.ts

We are now adding support for `jSGD` on Polygon

feat: adding support for jSGD

---

defi/src/adaptors/cli/backfillUtilities/getBackfillEvent.ts
defi/src/adaptors/handlers/getOverview/index.ts
defi/src/adaptors/handlers/getOverviewPre/index.ts
defi/src/adaptors/handlers/getProtocol/index.ts
defi/src/adaptors/handlers/helpers/generateProtocolAdaptorSummary.ts
defi/src/adaptors/handlers/notifyStatus.ts
defi/src/adaptors/utils/volumeCalcs.ts

This reverts commit 9df3bd63ebdcc4a1dcbf23d23e34a021da79096f.

Revert "Switch endpoints overviewPre->overview (#2027)"

---

defi/src/protocols/data2.ts

add oracle

---

defi/src/protocols/data2.ts

Uncommented the code about cranium exchange & fixed the contract info + twitter account

Edit informations - Cranium Exchange - #ID 2462

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts

dear llama sirs, 
requesting you review on some oracle updates for these protocols:
Torches 
https://twitter.com/PythNetwork/status/1603228775680217089?s=20&t=GEmIncz2L-WqqopV8f5S0Q
Kuswap
https://twitter.com/kuswapfinance/status/1603306063742177280?s=20&t=GEmIncz2L-WqqopV8f5S0Q
Thank you!

Oracle update for Kuswap and Torches

---

defi/src/protocols/data2.ts

- Added `cmcId` and `gecko_id `
- Updated chains

Edit information - Neptune Mutual - #ID 2327

---

coins/src/adapters/tokenMapping.json

fix tokenmapping

---

defi/src/protocols/data.ts

buffer binance

---

defi/src/protocols/data2.ts

fix token address algoblock

---

defi/src/protocols/data2.ts

messina description only

---

coins/src/adapters/nft/chainlink/priceFeeds.ts

Add Autoglyphs and Fidenza price floor oracles

---

defi/src/protocols/data.ts

new audit link

---

defi/src/protocols/data.ts

The official Twitter handle for Mimo is at https://twitter.com/mimo_labs

Update Twitter handle for Mimo

---

defi/src/protocols/data2.ts

fix category

---

defi/src/protocols/data.ts

add treasury liquity

---

defi/src/protocols/data2.ts

category valvet

---

defi/src/protocols/data2.ts

children sphere finance

---

coins/src/adapters/other/distressedAssets.ts

Add btcb to distressedAssets

---

coins/src/adapters/other/distressedAssets.ts

remove btcb from distress

---

defi/src/protocols/data2.ts

fix manifesto name

---

defi/src/protocols/data.ts

add treasury inverse finance frontier

add treasury inverse finance frontier

---

defi/src/protocols/data.ts

add treasury badger and fantohm

add treasury badger and fantohm

---

defi/src/protocols/data2.ts

- Fixes the company name spelling mistake

Fix a spelling mistake

---

defi/src/protocols/data2.ts

treasury jpeg listing

---

coins/src/adapters/tokenMapping.json

add IDLE token tokenmapping

---

defi/src/protocols/data2.ts

add token address

---

coins/src/adapters/tokenMapping.json

Added entry for recently launched Mars Protocols token MARS.

Add MARS IBC token on Kujira

---

defi/src/protocols/data.ts

fix module pancakeswap

---

defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

zyber last step

---

defi/src/protocols/parentProtocols.ts

bank of cronos parentProtocol (disable right now)

bank of cronos parentProtocol (disable right now)

---

coins/src/adapters/tokenMapping.json

add mapping for JTON (wrapped TON used by DeDust.io)

coins: add ton mapping

---

defi/src/protocols/data.ts

Dear Llama sirs,
Requesting your review to add Ribbon under Pyth as their oracle of use
Link below:
https://twitter.com/ribbonfinance/status/1587973259777429504

Added Ribbon oracle of use

---

defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

last step parentProtocol timeswap

last step parentProtocol timeswap

---

defi/src/protocols/data2.ts

audit links silo finance

---

defi/src/protocols/data2.ts

caviar audit

---

defi/src/utils/normalizeChain.ts

orachain fix

---

defi/src/protocols/data.ts
defi/src/protocols/parentProtocols.ts

update link cap.io

---

defi/src/protocols/data2.ts

Undo tBTC commit

---

defi/src/protocols/data2.ts

enable skullswap

---

defi/src/protocols/data2.ts

remove surfswap ,

---

defi/src/protocols/data2.ts

remove audit

---

coins/src/adapters/other/distressedAssets.ts

add MOR token to distress

---

defi/src/protocols/data2.ts

audit surfswap

---

defi/src/protocols/data.ts

correct chain v1

---

defi/src/protocols/data.ts
defi/src/protocols/parentProtocols.ts

Last step Balancer parentProtocol

Last step Balancer parentProtocol

---

defi/src/protocols/data2.ts

Undo ids commit

---

defi/src/protocols/data2.ts

remove dupliacated balancer v2

remove dupliacated balancer v2

---

defi/src/protocols/data.ts
defi/src/protocols/parentProtocols.ts

last step kyber

---

defi/src/protocols/data2.ts

decryption token address

---

defi/src/protocols/data2.ts

gm Llama sirs, requesting your review for Lifinity's oracle of use
https://twitter.com/PythNetwork/status/1580153998253838336?s=20

update Lifinity oracle usage

---

coins/src/adapters/tokenMapping.json

Umee recently added BNB to its platform.

feat: add Bnb for Umee 

---

defi/src/protocols/data2.ts

Dear llama sirs,
requesting your review on Marginfi's oracle of use
https://twitter.com/marginfi/status/1631384408426180608?s=46&t=4ajQwv7bRtbuYI4sBmpa6w
Thank you very much

Add Marginfi oracle

---

defi/src/protocols/parentProtocols.ts

fix Majik Finance parentProtocol

fix Majik Finance parentProtocol

---

defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

last step parentProtocol opensea

last step parentProtocol opensea

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts

Algebra Dex Forks list

---

defi/src/protocols/data2.ts

Correct token address x blue finance

Correct token address x blue finance

---

defi/src/protocols/data2.ts

description x blue

---

defi/src/protocols/data.ts

add treasury parrot protocol

---

defi/src/protocols/data2.ts

update category moret

---

defi/src/protocols/data2.ts

update sector finance descr

---

defi/src/protocols/data2.ts

update description maverick

---

defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

skullswap parent

---

defi/src/protocols/parentProtocols.ts

description ruby

---

defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

Merge LFGSwap Listings

---

defi/src/protocols/data2.ts

fix paraspace ape

---

defi/src/protocols/data.ts

delist evolutionland

---

defi/src/protocols/data2.ts

add audit rehold

---

defi/src/protocols/data.ts

remove fork

---

defi/src/protocols/data2.ts

add fork field

---

defi/src/protocols/data.ts

add treasury orv

---

defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

spin parent last step

---

coins/src/adapters/other/distressedAssets.ts

add cino distressassets

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

disable parentProtocol for morphex

disable parentProtocol for morphex

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

last step arrakis parentProtocol

last step arrakis parentProtocol

---

defi/src/protocols/data.ts

add fork information (synapse and hop)

add fork information (synapse and hop)

---

defi/src/protocols/data2.ts

update audit link archimedes

---

defi/src/protocols/data2.ts

fix fork information ramses

---

coins/src/adapters/index.ts
coins/src/adapters/other/index.ts
coins/src/adapters/other/realt.ts
coins/src/adapters/readme.md

They only have the latest price using this API, I don't know if it's fine.
I set the confidence to 1, the price from the API is the price they are selling it to you for and they will buy it back from you with a 3% fee.

add RealT tokens

---

defi/src/protocols/data2.ts

add treasury openxswap

---

defi/src/protocols/data2.ts

new description arc swap

---

defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

last step parentProtocol fairyswap

last step parentProtocol fairyswap

---

defi/src/protocols/data.ts

audit link usd+

---

coins/src/adapters/utils/database.ts

Reverts DefiLlama/defillama-server#2599

Revert "static decimals, symbol"

---

defi/src/protocols/data2.ts

apex protocol website link

---

defi/src/protocols/data2.ts

Update oracle Apex Protocol

---

defi/src/adaptors/cli/backfillUtilities/getBackfillEvent.ts
defi/src/adaptors/handlers/getOverviewProcess/index.ts

Reverts DefiLlama/defillama-server#2611

Revert "Add extra types for royalties"

---

defi/src/protocols/data2.ts

add module

---

defi/src/protocols/data.ts

update cg id for multichain

---

coins/src/genesisBlockTimes.ts
coins/src/getBlock.ts

Reverts DefiLlama/defillama-server#2657

Revert "zksync block times"

---

defi/src/protocols/data.ts

gamma description

---

defi/src/protocols/data2.ts

add description to metropolis

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

Remove Mux parentProtocol

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts

Integral
SolidLizard
PowerPool
Sovryn governance

Governance

---

coins/src/adapters/other/distressedAssets.ts

Add FEG to distressAsset list

---

coins/src/adapters/other/distressedAssets.ts

add FEG distressAsset list

---

defi/src/protocols/data2.ts

fix ids server

---

defi/src/protocols/data.ts
defi/src/protocols/data2.ts

We updated the mux and mcdex descriptions to make them more accurate and easy to understand.

update MCDEX, MUX info

---

defi/src/protocols/data.ts

fix Synthetix name

---

defi/src/protocols/data2.ts

add info starfish

---

defi/src/protocols/data2.ts

update description dolomite

---

defi/src/protocols/data.ts

Uniswap V2 fork 1/4

---

defi/src/protocols/data2.ts
defi/src/protocols/parentProtocols.ts

Update twitter and website links WOOFi

Update twitter and website links WOOFi

---

defi/src/protocols/data2.ts

add treasury empyreal

---

defi/src/protocols/data2.ts

update descr woofi swap
